### ISSUE TITLE
Expand README.md Requirements

### ISSUE THREAD

**Issue by HallerPatrick** [Kethku/neovide#142] opened 2020-02-18 11:08 UTC
I am trying to setup neovide on my windows machine I think the README.md lacks requirements, like the VULKAN SDK for windows.

**Comment by Kethku** [comment] 2020-02-18 15:45
Can you give more details as to what is going wrong? On modern windows systems with a supported gpu, the vulkan drivers should be automatically available

**Comment by HallerPatrick** [comment] 2020-02-18 15:53
Okay this may seem to be a problem of my own. 

I tried to setup neovide in a virtual machine which runs Windows 7 (host is windows 10). The skulpin docu mentions that the LunarG Vulkan SDK is required, which I tried to install unsuccessfuly.

**Comment by Kethku** [comment] 2020-02-18 16:09
Lunarg vulkan sdk is only necessary on Linux. The issue is likely the virtual machine because it requires gpu support which is handled poorly on VM setups

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment] 2020-02-18 16:10
In the future we may add support for opengl but I'm fairly confident that even then it won't work in a vm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment] 2020-02-18 17:46
I'm going to close this as out of scope.

**Closed by Kethku** 2020-02-18 17:46 UTC
