### ISSUE TITLE
Issue when compiling with sdl2 + Vulkan

### ISSUE THREAD

**Issue by phaazon** [Kethku/neovide#352] opened 2020-09-06 10:21 UTC
I have installed `sdl2` (Archlinux) and I’m trying to compile with `cargo build --release`. I’m hitting these errors:

[cargo.txt](https://github.com/Kethku/neovide/files/5179430/cargo.txt)

**Comment by j4qfrost** [comment] 2020-09-06 14:13
There are two ways to fix this, remove the build dependencies for Windows
or build with CFLAGS=-fcommon. It's a weird bug.

**Comment by Kethku** [comment] 2020-09-06 17:19
Seems like something we should report upstream maybe?

Thanks,
Keith
________________________________

**Comment by j4qfrost** [comment] 2020-09-06 17:24
I’m not actually sure how to resolve this. I think it has to do with double importing sdl2. We do a cfg check for Windows when including sdl as a build dependency, but for some reason it’s still being injected into Arch Linux builds. This could be a bug in rust itself, but I’m still trying to articulate the issue.

**Comment by phaazon** [comment] 2020-09-07 00:10
I think it might be a regression, because I have a very typical issue with luminance, [here](https://github.com/phaazon/luminance-rs/issues/445) — I got the same kind of errors.

**Comment by j4qfrost** [comment] 2020-09-07 00:20
Yeah, I wish we could inject CFLAGS through Cargo.toml. Would save me
headaches tracking down the issue. Though the issue you linked may have the
possibility of being unrelated.

**Comment by j4qfrost** [comment] 2020-09-28 16:42
This is resolved with https://github.com/Kethku/neovide/pull/360 @phaazon

**Comment by j4qfrost** [comment] 2021-04-23 17:11
-fcommon this seems to have reared its ugly head again. Built on master for Ubuntu and had to add the -fcommon flag. Will reopen to investigate.

**Comment by j4qfrost** [comment] 2021-05-09 04:25
Can't reproduce, not sure what happened. Closing.

**Closed by j4qfrost** 2021-05-09 04:25 UTC
Labels: bug
