### ISSUE TITLE
mouse selection in wsl mod doesn't work

### ISSUE THREAD

**Issue by peach-lasagna** [Kethku/neovide#470] opened 2021-02-08 22:29 UTC
If i run neovide without `--wsl` flag i can make selection with right mouse button:
![изображение](https://user-images.githubusercontent.com/59787538/107289359-7de99c80-6a97-11eb-9b52-a8580cbc344f.png)
with flag - no.

**Comment by Kethku** [comment] 2021-02-12 04:49
Are the versions of neovim the same between the two?

**Comment by peach-lasagna** [comment] 2021-02-12 13:10
yep

**Comment by Kethku** [comment] 2021-02-17 07:37
That is strange and I can reproduce it. I have honestly no idea why this would happen...

**Comment by calvinkosmatka** [comment] 2021-02-22 06:57
@peach-lasagna @Kethku I couldn't get selection to work under Windows or WSL at first - `:set mouse=a` made it work on both for me, does that fix it for you?

**Comment by Kethku** [comment] 2021-02-22 06:59
duh. That makes a ton of sense! @peach-lasagna I can no longer reproduce this.

**Comment by Kethku** [comment] 2021-02-24 09:24
@peach-lasagna I think I'm going to close this because I'm pretty sure @calvinkosmatka pointed out the issue.

**Closed by Kethku** 2021-02-24 09:24 UTC
Labels: bug, help wanted

**Comment by peach-lasagna** [comment] 2021-02-24 12:34
Oh, yes! this works. Thank you!
