### ISSUE TITLE
Tab completion popup window in command mode has disappeared in newest neovim + neovide

### ISSUE THREAD

**Issue by Hubro** [Kethku/neovide#773] opened 2021-06-29 21:19 UTC
**Describe the bug**

Tab completing stuff in command mode doesn't bring up a popup window in Neovide. In nvim in the terminal, it works as expected.

**To Reproduce**
1. Open Neovide
2. Type `:let g:neovide_`
3. Press Tab a bunch of times
4. No popup appears

**Expected behavior**

I expected a popup to appear like in nvim.

**Screenshots**

Neovide:

![image](https://user-images.githubusercontent.com/597206/123868688-54d78480-d930-11eb-859a-b3b25279064c.png)

Neovim:

![image](https://user-images.githubusercontent.com/597206/123868699-586b0b80-d930-11eb-8ff0-ebd9c46308f5.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: `main` branch (`2fc74f83ca2ac167df8607ed2e0f29122ec5f167`)
 - Neovim Version `master` branch (`v0.5.0-dev+1459-g384f9870f`)

**Please run `neovide --log` and paste the contents of the `.log` file here:**

https://gist.githubusercontent.com/Hubro/d53c69b04bb71035accc021790ffe1db/raw/066de6b886f69fa1bac5642660787bee5bfcb8f8/neovide_rCURRENT.log

**Comment by Kethku** [comment] 2021-06-29 21:43
Do you have multgrid enabled? This works on my machine

**Comment by Hubro** [comment] 2021-06-29 21:47
> Do you have multgrid enabled? This works on my machine

Yep, it's enabled. I'm smooth scrolling in the same window. :thinking:

**Comment by Hubro** [comment] 2021-06-29 21:53
I just tried running with `-u NONE` to launch a completely vanilla nvim, still doesn't work. So it's not the fault of my plugins or vim config.

**Comment by Kethku** [comment] 2021-06-29 21:54
Let me update to *latest* latest and see

**Comment by Kethku** [comment] 2021-06-29 21:57
Ok you're absolutely right. That means in the last week or so a regression was introduced upstream.

**Comment by Hubro** [comment] 2021-06-29 22:01
> Ok you're absolutely right. That means in the last week or so a regression was introduced upstream.

Ok, glad you were able to reproduce it. Are you on top of reporting it? I have no idea where I would even start :sweat_smile:

**Comment by Kethku** [comment] 2021-06-29 22:03
Well first step, I'm trying to find which commits look suspicious by reading commit messages. I don't have neovim building on my machine atm, so this may be a little difficult to triangulate where the problem is.

Once thats figured out I can then either determine if it was a bug fix and I was just programming to the bug or if its really a regression.

Do you have any ideas how we might find the problem commit upstream?

**Comment by Kethku** [comment] 2021-06-29 22:07
https://github.com/neovim/neovim/pull/14137 This one looks suspicious. At least it has to do with the PUM which I believe is the completion menu used here.

**Comment by Hubro** [comment] 2021-06-29 22:09
> [neovim/neovim#14137](https://github.com/neovim/neovim/pull/14137) This one looks suspicious. At least it has to do with the PUM which I believe is the completion menu used here.

I can probably build neovim in a jiffy, I'll test if that commit is the perpetrator.

**Comment by Kethku** [comment] 2021-06-29 22:09
Nah I figured it out. Fix incoming

**Comment by Hubro** [comment] 2021-06-29 22:10
> Nah I figured it out. Fix incoming

Haha awesome :grin: Were you indeed relying on a bug that got fixed?

**Comment by Kethku** [comment] 2021-06-29 22:11
Yeah funny enough this issue had been happening in reverse, so a couple of days ago I rammed my head through the wall and made a "fix" that just programmed to upstream behavior. Turns out the bug had already been fixed and I was just on an old version of master.

I just pushed a fix. Thanks for the report!

**Closed** 2021-06-29 22:12 UTC
Labels: bug

**Comment by Hubro** [comment] 2021-06-29 22:13
> Yeah funny enough this issue had been happening in reverse, so a couple of days ago I rammed my head through the wall and made a "fix" that just programmed to upstream behavior. Turns out the bug had already been fixed and I was just on an old version of master.
> 
> I just pushed a fix. Thanks for the report!

Awesome! Thanks for the quickest fix I've ever seen! :grin:

**Comment by Kethku** [comment] 2021-06-29 22:15
We aim to please ;)
