### ISSUE TITLE
Cursor disappears when searching characters

### ISSUE THREAD

**Issue by svermeulen** [Kethku/neovide#98] opened 2020-02-01 05:41 UTC
Neovim version: `NVIM v0.4.3` installed via brew
OS: `osx`

Minimal vimrc:
```
set lazyredraw
```

Repro steps:
* Open neovide
* Execute `/` and type some characters until the cursor goes invisible
* Hit escape
* Cursor should now be invisible while navigating buffer

**Comment by Kethku** [comment] 2020-02-01 05:45
Woah I've never heard of this option. I will look into it.

**Comment by Kethku** [comment] 2020-02-01 19:59
I cannot reproduce this issue. I am running neovim 4.2 and do not see the problem

**Comment by Kethku** [comment] 2020-02-01 20:09
I just updated to nightly and don't see the issue their either.

**Comment by SirJson** [comment] 2020-02-01 20:26
He just found the setting I lost, lazyredraw is causing #53 for me. 

I remember reading about lazyredraw [here](https://github.com/tpope/vim-sensible/issues/78) and adding it to this machines init.vim, but I never put that into my backup init.vim. 

That's why the problem disappeared when I restored my usual rc files.

Until the cause is found adding `set nolazyredraw` instead of  `set lazyredraw` will fix it.

**Comment by Kethku** [comment] 2020-02-01 20:28
Wait what. Lazyredraw is causing a font load error for you?

**Comment by SirJson** [comment] 2020-02-01 20:29
I meant #58 sorry for the confusion. 😄

**Comment by Kethku** [comment] 2020-02-01 20:32
Ah that makes much more sense. And now that you mention it, I've noticed this happening on my machine now as well. I'm considering making an upstream neovim issue as I don't think it makes sense for the cursor to ever move to the powerline. Thoughts?

**Comment by Kethku** [comment] 2020-02-01 20:33
Oh also I can now repro the above steps. Thats a very weird bug

**Comment by Kethku** [comment] 2020-02-01 20:34
I need better logging to track this down

**Comment by SirJson** [comment] 2020-02-01 20:34
Yes reading the issue on the vim-sensible project makes it pretty clear that lazyredraw not only causing issues with some terminals but there are also reports of nvim completely breaking because of it. Maybe you can ignore this setting somehow?

**Comment by Kethku** [comment] 2020-02-01 20:35
Weirdly I'm not using the setting at all its all internal stuff. I could track the option and disable it with a message, but that feels like a hack since it definitely improves macro performance...

**Comment by SirJson** [comment] 2020-02-01 20:37
Does it though in neovide? As I understand it lazyredraw should only make sense in a terminal context because the way you draw things is different than a terminal would do it. Also your drawing loop isn't tied to the neovim update loop isn't it?

**Comment by Kethku** [comment] 2020-02-01 20:38
Oh very interesting. The bug happens even without lazyredraw. Searching, typing random characters, and then pressing escape causes the cursor to stay missing.

**Comment by Kethku** [comment] 2020-02-01 20:40
I have no idea what lazyredraw does.

Neovide's render loop is not tied to the neovim update loop so youre probably right. That said, the jumping the cursor to the command line is clearly an internal effect of lazyredraw so I'm not sure whats happening.

**Comment by SirJson** [comment] 2020-02-01 20:51
I guess it does what it says in the name. 

**NOTE: The next few lines are just based on reading on neovim and speculation on how it works. I have never implemented a neovim client nor worked on neovim.**

Even tough neovide is drawing everything, lazyredraw probably activates something in vim that reduces the amount of drawing that is happening in the context of a terminal. My understanding is that building your own neovim client is all about IPC and if neovim does less it will generate less events or not all that would have been created. 

In the terminal that is okay because there usually some default behaviour that makes the cursor go back but external applications have to either also implement that behaviour or just ignore it.

**Comment by Kethku** [comment] 2020-02-01 21:18
This seems reasonable to me. Disabling lazyredraw is a good plan

**Comment by Kethku** [comment] 2020-02-03 04:47
Done. Disabling on startup. If this causes problems, either open an issue or comment here and I will figure something more out.

**Comment by justinmk** [comment] 2020-02-03 04:57
fwiw this is probably something that should be resolved in Nvim core, since it is intended that multiple UIs (including TUI) may be attached to one Nvim server.

**Comment by Kethku** [comment] 2020-02-03 04:58
Interesting. Would you like me to make an issue in nvim? I can give some details and link back to this issue.

**Comment by justinmk** [comment] 2020-02-03 05:06
> I can give some details and link back to this issue.

would be great!

**Comment by Kethku** [comment] 2020-02-03 05:21
Done: https://github.com/neovim/neovim/issues/11806

**Comment by Kethku** [comment] 2020-02-03 05:21
Swapping this issue over to the original issue

**Comment by Kethku** [comment] 2020-02-03 06:25
The original issue is an upstream problem which I believe will be fixed by https://github.com/KillTheMule/nvim-rs/pull/13 or something similar.

**Comment by Kethku** [comment] 2020-02-04 14:39
This should be fixed.

**Closed by Kethku** 2020-02-04 14:39 UTC
Labels: bug, waiting

**Comment by svermeulen** [comment] 2020-02-23 01:04
So be clear, is `lazyredraw` supported in neovide?  I actually find this setting to be really helpful performance wise in both terminal vim and nvim-qt

**Comment by Kethku** [comment] 2020-02-23 05:08
There is an upstream issue here: https://github.com/neovim/neovim/issues/11806 Until the core issue is fixed, it is not supported.
