### ISSUE TITLE
Neovide crashes

### ISSUE THREAD

**Issue by Zuzuk-null** [Kethku/neovide#676] opened 2021-05-24 03:38 UTC
```Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/runner/.cargo/git/checkouts/skribo-3c422fce25a33836/a35c876/src/collection.rs:130:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:182:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:2161:9
   6: <skribo::collection::Itemizer as core::iter::traits::iterator::Iterator>::next
             at /home/runner/.cargo/git/checkouts/skribo-3c422fce25a33836/a35c876/src/collection.rs:130:32
   7: skribo::session::LayoutSession<S>::create
             at /home/runner/.cargo/git/checkouts/skribo-3c422fce25a33836/a35c876/src/session.rs:77:34
   8: neovide::renderer::fonts::caching_shaper::CachingShaper::shape_cached
   9: neovide::renderer::Renderer::draw_foreground
  10: neovide::renderer::rendered_window::RenderedWindow::handle_window_draw_command
  11: neovide::renderer::Renderer::draw_frame
  12: skulpin_renderer::renderer::Renderer::draw
  13: neovide::window::window_wrapper::Sdl2WindowWrapper::draw_frame
             at /home/runner/work/neovide/neovide/src/window/sdl2/mod.rs:368:13
  14: neovide::window::window_wrapper::start_loop
             at /home/runner/work/neovide/neovide/src/window/sdl2/mod.rs:508:15
  15: neovide::window::create_window
             at /home/runner/work/neovide/neovide/src/window/mod.rs:112:5
  16: neovide::main
             at /home/runner/work/neovide/neovide/src/main.rs:180:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by ErikMayrhofer** [comment] 2021-05-24 08:33
Looks like a duplicate of #670?

**Comment by PyGamer0** [comment] 2021-05-24 08:35
definitely a duplicate; install `noto fonts` should work

**Closed** 2021-05-24 13:59 UTC
