### ISSUE TITLE
[OSX] got this error when trying to run the binary   "ERROR [neovide::error_handling] Could not locate or start the neovim process: No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by SakiiR** [Kethku/neovide#366] opened 2020-09-23 13:36 UTC
```
ERROR [neovide::error_handling] Could not locate or start the neovim process: No such file or directory (os error 2)
thread 'tokio-runtime-worker' panicked at 'Could not locate or start the neovim process: No such file or directory (os error 2)', src/error_handling.rs:5:5
stack backtrace:
   0:        0x1095004d2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h43ad886765c40c91
   1:        0x10941acde - core::fmt::write::he548ee6ce743d415
   2:        0x1094ff829 - std::io::Write::write_fmt::hf0a8cad0ca2251e3
   3:        0x1094ff36a - std::panicking::default_hook::{{closure}}::h166f557a03fd111a
   4:        0x1094fe6de - std::panicking::rust_panic_with_hook::h2db5049a14746a6d
   5:        0x109a61729 - std::panicking::begin_panic::h0a05415f8d09c2f5
   6:        0x1093ab2eb - neovide::error_handling::show_error::hf7d12f3745753c01
   7:        0x10938d73b - neovide::bridge::start_process::{{closure}}::h4ed987069c262f8e
   8:        0x1093885f9 - <std::future::GenFuture<T> as core::future::future::Future>::poll::hb3b99ab4d3318f43
   9:        0x109398ce8 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3bc90a64e410fafa
  10:        0x10939e6f6 - tokio::runtime::task::raw::poll::hfd1d0acbbb21f1f1
  11:        0x109527fde - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::h6edbcf3ec0ae63a6
  12:        0x109527d38 - tokio::runtime::thread_pool::worker::Context::run_task::h41b7158f8d5ac2cb
  13:        0x10951d2fe - tokio::runtime::task::raw::poll::h043fc79dd7e83da9
  14:        0x109517535 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6082cfeb5814c8a7
  15:        0x109515812 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1e1e64ff602e95c
  16:        0x109511a8e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h833ca8069ad09045
  17:        0x1095131a7 - std::sys::unix::thread::Thread::new::thread_start::hf0162e8f94e1ff75
  18:     0x7fff72930109 - _pthread_start
objc[59033]: Class MVKBlockObserver is implemented in both /Applications/Neovide.app/Contents/Frameworks/libMoltenVK.dylib (0x10f1e1be0) and /usr/local/Caskroom/vulkan-sdk/1.2.148.0/macOS/lib/libMoltenVK.dylib (0x10facb890). One of the two will be used. Which one is undefined.
thread 'main' panicked at 'Could not create vulkan surface: ERROR_INITIALIZATION_FAILED', /Users/runner/.cargo/git/checkouts/skulpin-d51ad4b3eb824ff8/7ae2c4f/skulpin-renderer/src/device.rs:48:23
stack backtrace:
   0:        0x1095004d2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h43ad886765c40c91
   1:        0x10941acde - core::fmt::write::he548ee6ce743d415
   2:        0x1094ff829 - std::io::Write::write_fmt::hf0a8cad0ca2251e3
   3:        0x1094ff36a - std::panicking::default_hook::{{closure}}::h166f557a03fd111a
   4:        0x1094fe6de - std::panicking::rust_panic_with_hook::h2db5049a14746a6d
   5:        0x10950341a - rust_begin_unwind
   6:        0x109a6469f - core::panicking::panic_fmt::hd7d9261f4286def0
   7:        0x109a64c25 - core::option::expect_none_failed::hb279b852aa887524
   8:        0x1094fa010 - skulpin_renderer::device::VkDevice::new::hdfbd1a5ee75181b2
   9:        0x1093b069d - neovide::window::ui_loop::h352f71c2beaf73ff
  10:        0x109377882 - neovide::main::hdaa1d3175fac3baa
  11:        0x109392aa6 - std::rt::lang_start::{{closure}}::h8fe6dcf1d15454b4
  12:        0x10937760a - main

```

**Comment by Kethku** [comment] 2020-09-27 02:20
Do you nave neovim installed?

**Comment by SakiiR** [comment] 2020-09-29 08:29
Yes it is :(

**Comment by j4qfrost** [comment] 2020-10-08 20:07
Are you still having this issue?

**Comment by clason** [comment] 2020-10-09 06:26
The usual cause for such an issue is that applications started via the finder do not have the correct environment (in particular, `PATH`) set. You can see if this is the case if things work when you open a terminal and run the `Neovide.app/Contents/MacOS/neovide` binary directly (you might have to `chmod +x neovide` first) -- in this case, neovide inherits the (hopefully correct) environment from the terminal.

Apple keeps messing with the BSD layer, so I'm not 100% sure where to put environment variables that should be set system-wide, but you could try adding `/usr/local/bin/` in front of the path in `.zshenv` in your home directory (which you'd need to create if it doesn't exist).

**Comment by j4qfrost** [comment] 2020-10-09 06:46
Well the issue is that he is starting this from the terminal and he can already run the binary, so the Finder wouldn't be the cause of the crash. This does look like a PATH error though. @SakiiR doesn running nvim separately work?

**Comment by SakiiR** [comment] 2020-10-09 08:22
I re-downloaded the last release in place and got a new issue :/

<img width="1110" alt="sc 2020-10-09 at 10 21 48" src="https://user-images.githubusercontent.com/9950578/95560251-4ef3e900-0a19-11eb-993d-f62c822a92b1.png">

**Comment by SakiiR** [comment] 2020-10-09 08:23
I can run neovim perfectly:

<img width="1353" alt="sc 2020-10-09 at 10 22 44" src="https://user-images.githubusercontent.com/9950578/95560320-67640380-0a19-11eb-8847-eada05d2d46c.png">

**Comment by j4qfrost** [comment] 2020-10-09 08:27
Can you run with --log and paste the output? What terminal is that? It might be possible that the PATH isn't invoked correctly.

**Comment by SakiiR** [comment] 2020-10-09 08:48
No Logs ...

<img width="1164" alt="sc 2020-10-09 at 10 47 47" src="https://user-images.githubusercontent.com/9950578/95562765-e1e25280-0a1c-11eb-97db-be98e29ad1a0.png">

It's iterm2, zsh etc everything is normal xD

**Comment by SakiiR** [comment] 2020-10-09 08:50
Oh my bad , logs are in a file:

```
INFO [neovide::bridge] Close watcher started
INFO [neovide::bridge] Neovim process attached
INFO [neovide::bridge] UiCommand processor started
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::editor] Option set Pumblend(0)
TRACE [neovide::editor] Option set ShowTabLine(1)
TRACE [neovide::editor] Option set TermGuiColors(false)
TRACE [neovide::editor] Option set Unknown("ttimeout", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ttimeoutlen", Integer(PosInt(50)))
TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_termcolors", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set TermGuiColors(true)
TRACE [neovide::editor] Option set GuiFont("Monofur Nerd Font:16")
TRACE [neovide::editor] Option set ShowTabLine(2)
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_lifetime: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_lifetime')
WARN [neovide::settings] Initial value load failed for extra_buffer_frames: Error processing request: 1 - 'Key not found: neovide_extra_buffer_frames')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_speed: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_speed')
WARN [neovide::settings] Initial value load failed for refresh_rate: Error processing request: 1 - 'Key not found: neovide_refresh_rate')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_phase: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_phase')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_density: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_density')
WARN [neovide::settings] Initial value load failed for cursor_vfx_particle_curl: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_particle_curl')
WARN [neovide::settings] Initial value load failed for no_idle: Error processing request: 1 - 'Key not found: neovide_no_idle')
WARN [neovide::settings] Initial value load failed for cursor_animation_length: Error processing request: 1 - 'Key not found: neovide_cursor_animation_length')
WARN [neovide::settings] Initial value load failed for cursor_trail_size: Error processing request: 1 - 'Key not found: neovide_cursor_trail_size')
WARN [neovide::settings] Initial value load failed for cursor_vfx_opacity: Error processing request: 1 - 'Key not found: neovide_cursor_vfx_opacity')

```

**Comment by grem11n** [comment] 2021-01-07 21:26
It's just a wild guess, but maybe it's related to the NeoVim version? I've noticed that you're using v0.5.0, which is not a release version.

I have problems with Neovide as well with v0.5.0.

My setup:
* iTerm2 3.4.3
* NVIM v0.5.0-35325ddac
* Neovide is built following the instructions from the README.

Here's are some logs:
```
INFO [neovide::bridge] Close watcher started
INFO [neovide::bridge] Neovim process attached
INFO [neovide::bridge] UiCommand processor started
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::editor] Option set Unknown("mousefocus", Boolean(false))
TRACE [neovide::editor] Option set Pumblend(0)
TRACE [neovide::editor] Option set ShowTabLine(1)
TRACE [neovide::editor] Option set TermGuiColors(false)
TRACE [neovide::editor] Option set Unknown("ttimeout", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ttimeoutlen", Integer(PosInt(50)))
TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_termcolors", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_cmdline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_popupmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_tabline", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_wildmenu", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_messages", Boolean(false))
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor::grid] Editor cleared
TRACE [neovide::editor] Option set TermGuiColors(true)
TRACE [neovide::editor] Cursor off
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Cursor on
TRACE [neovide::editor] Option set ShowTabLine(2)
TRACE [neovide::editor] Cursor off
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Cursor on
TRACE [neovide::editor] Cursor off
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Cursor on
TRACE [neovide::editor] Cursor off
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Cursor on
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::editor] Region scrolled
TRACE [neovide::editor] Image flushed
TRACE [neovide::redraw_scheduler] Next frame queued
```

**Comment by Kethku** [comment] 2021-01-07 23:03
I use 0.5 nightly builds as my daily driver on main

**Comment by Kethku** [comment] 2021-06-13 23:46
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.

**Closed by Kethku** 2021-06-13 23:46 UTC
Labels: bug
