### ISSUE TITLE
Add options to disable cursor animation in insert or command line

### ISSUE THREAD

**Issue by noelzubin** [Kethku/neovide#85] opened 2020-01-30 07:11 UTC
I absolutely love this feature. But i wish i could disable it in insert mode. because it feels like there is an input lag when i type in insert mode. Although there isnt one.

**Comment by Kethku** [comment] 2020-01-30 07:18
Good call. I will look into it. This may get me to actually build a setting system...

**Comment by noelzubin** [comment] 2020-01-30 07:32
Thanks @Kethku

**Comment by Kethku** [comment] 2020-02-01 05:27
Adding to this the requirement that it should also have an option to disable animations to and from the commandline. Too many setups will animate to the line count or similar which is super distracting. It would be nice to instead have the cursor jump there, but remember where it was so that when it jumps back if it is in a different position, it will animate to the new position from the previous location instead of the command line or just jumping to the new place.

This is super important for keybindings which might incidentally write to the commandline.

**Comment by MobiusHorizons** [comment] 2020-02-05 07:34
+1. I specifically find it distracting that it jumps to the bottom row whenever I enter insert mode, so the cursor is no longer resting at it's original location.

**Comment by justinmk** [comment] 2020-02-05 08:09
> This may get me to actually build a setting system...

fwiw, Nvim has `dictwatcheradd()` which was intended for this purpose, i.e. so plugins can listen to options changes. Example:

```
silent! call dictwatcherdel(g:, 'foo_*', 'OnDictChanged')
function! OnDictChanged(d,k,z)
  echomsg string(a:k) string(a:z)
endfunction
call dictwatcheradd(g:, 'foo_*', 'OnDictChanged')
let g:foo_setting = 'baz'
```

**Comment by Kethku** [comment] 2020-02-16 08:38
Option support implemented like @justinmk suggested is now done. Closing this in favor of https://github.com/Kethku/neovide/issues/117

**Closed by Kethku** 2020-02-16 08:38 UTC
Labels: enhancement
