### ISSUE TITLE
Unable to trigger fcitx5 when using neovide

### ISSUE THREAD

**Issue by Avimitin** [Kethku/neovide#1006] opened 2021-10-10 13:01 UTC
**Describe the bug**
The fcitx5 App is an input method engine that I use for input Chinese. It works on most of my desktop applications like Neovim-QT, Telegram, and Firefox...etc. I recently switched to use neovide. It meets my needs very well, except for one thing: I can't use the hotkey to trigger the input method.

I am using `<CTRL>+<SHIFT>` and `<CTRL>+<SPACE>` to trigger my fcitx5. When I press `<CTRL>+<SPACE>`, it triggers the inner completion menu, and when I press `<CTRL>+<SHIFT>`, nothing happens.

It's weird because whatever the hotkey I used, the nvim-qt can work as expected, so maybe it is not my neovim configuration error. Moreover, no error report from `fcitx5-diagnose`, so maybe it is not my fcitx5 configuration error.

But I can't find any issues related to fcitx5, so I am here to ask for help.

**To Reproduce**
1. Install packages [fcitx5](https://archlinux.org/packages/?name=fcitx5), [fcitx5-im](https://archlinux.org/groups/x86_64/fcitx5-im/), [fcitx5-rime](https://archlinux.org/packages/?name=fcitx5-rime)
2. Set environment variable like below:
```text
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT4_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export INPUT_METHOD=fcitx
```
3. Run `fcitx-configtool` and add rime below the `Keyboard-English`

![image](https://user-images.githubusercontent.com/30021675/136696391-ff1faf59-221c-4d9b-ac4d-1cea92192246.png)

4. Set hotkey like below

![image](https://user-images.githubusercontent.com/30021675/136696466-e21c5926-d773-425a-8867-2061fc3fab66.png)

5. Open neovide and try to press those hotkey

**Expected behavior**

The behavior I expect is like nvim-qt. I've recorded a video to show the difference.

https://user-images.githubusercontent.com/30021675/136696662-a735b535-f87e-4fad-9248-a638e9839233.mp4

**Desktop (please complete the following information):**
 - OS: Linux 5.14.9-arch
 - Neovide Version: Neovide 0.8.0 from [neovide-git](https://aur.archlinux.org/packages/neovide-git/)
 - Neovim Version [e.g. 0.5.0]: NVIM v0.6.0-dev+132-g7d2233fad

**Please run `neovide --log` and paste the contents of the `.log` file here:**

Log:

```text
TRACE [neovide] Neovide version: 0.8.0
```

**Additional context**
My rime settings: https://github.com/Avimitin/rime
My NeoVIM settings: https://github.com/Avimitin/nvim
fcitx5 diagnose output: https://pastebin.com/QQ0tERtZ

**Comment by kaigedong** [comment] 2022-01-05 02:21
Same problem

**Comment by blue7wings** [comment] 2022-04-29 17:12
Same problem😭

**Comment by aj3423** [comment] 2022-05-02 12:28
same here with 0.9.0

**Comment by askfiy** [comment] 2022-05-27 07:01
same

**Comment by 15059760257** [comment] 2022-06-20 05:27
> same here with 0.9.0
same

**Comment by Icy-Thought** [comment] 2022-07-28 16:39
Anyone that found a solution to this problem?

**Comment by dontdieych** [comment] 2022-10-13 15:46
same here

**Comment by cnfczn** [comment] 2022-11-10 05:25
same 0.10.3

**Comment by drednoot** [comment] 2022-11-20 15:33
Same here with 0.10.3

**Comment by vizee** [comment] 2022-11-29 03:29
> Anyone that found a solution to this problem?

I guess it needs to update winit

**Comment by elytraflyer** [comment] 2023-01-21 04:41
I builded it from source code,and the problem isn't fixed

> > Anyone that found a solution to this problem?
> 
> I guess it needs to update winit

**Comment by vizee** [comment] 2023-01-28 05:46
> I builded it from source code,and the problem isn't fixed
> 
> > > Anyone that found a solution to this problem?
> > 
> > 
> > I guess it needs to update winit

**Comment by realth000** [comment] 2023-02-03 07:19
Same problem.
Any workaround?

**Comment by yzlnew** [comment] 2023-03-07 12:46
Can't input Chinese in MacOS using squirrel as well.

**Comment by XChy** [comment] 2023-05-08 15:34
Same with 0.10.3 still

**Comment by fredizzimo** [comment] 2023-06-18 13:04
This should be fixed by #1899, it would be great if you can test that.

**Comment by realth000** [comment] 2023-06-19 15:02
Any config required?
The release build from commit 402382c0 seems not fix this.
Tested with arch linux + hyprland, with/without `WINIT_UNIX_BACKEND=x11`, in vim insert mode and command mode.

**Comment by fredizzimo** [comment] 2023-06-19 15:09
Also note that I'm still working on the pre-edit support. And the positioning of the popup also has some issues and waiting for https://github.com/rust-windowing/winit/issues/2886

**Comment by fredizzimo** [comment] 2023-06-19 19:40
It looks like it's not fixed on X11 yet. But Wayland should work, at least if you follow the above instructions.

**Comment by wengxt** [comment] 2023-06-20 18:50
@fredizzimo you might need to go to fcitx5's config of xim frontend and check "on the spot" and then restart fcitx5 if you want to try preedit on xim.

There's some historical reason that xim's preedit is not enabled by default.

https://bugs.freedesktop.org/show_bug.cgi?id=1580
https://gitlab.freedesktop.org/xorg/lib/libx11/-/commit/62c3337d89d31e0d3ed807004e73ad711fad3342

**Comment by fredizzimo** [comment] 2023-06-30 16:44
X11 should now work with  #1899

**Closed as completed** 2023-07-06 13:37 UTC
Labels: bug
