### ISSUE TITLE
Ligatures render incorrectly

### ISSUE THREAD

**Issue by TheConfuZzledDude** [Kethku/neovide#198] opened 2020-03-16 22:23 UTC
As shown in the video, ligatures appear to be offset to the right

![image](https://giant.gfycat.com/DevotedThickAfricanwildcat.gif)

**Comment by Kethku** [comment] 2020-03-16 22:48
What platform?
What is guifont set to?
Release or build from source?

**Comment by TheConfuZzledDude** [comment] 2020-03-17 00:40
Platform is Arch Linux 5.5.9-zen1-2-zen 
WM is the latest Sway git (though I believe this runs in XWayland so that doesn't make much of a difference)
guifont is set to `FiraCode\ Nerd\ Font\ Mono:h14:style=Medium,Regular`
Version is latest source build, through the neovide-git AUR package

**Comment by Kethku** [comment] 2020-03-17 21:43
Hmmm. Thats very strange... I'm sort of at a loss for why this happens. Does it happen if you remove the guifont causing neovide to use the embedded fonts?

**Comment by TheConfuZzledDude** [comment] 2020-03-17 23:22
Removing the set guifont entirely just does this...
![image](https://user-images.githubusercontent.com/3160203/76910479-0078d480-68a6-11ea-84b6-d782e3520730.png)
Possibly related but probably not is the fact that the mouse clicking is very offset from where it should be

**Comment by Kethku** [comment] 2020-03-18 14:41
What happens if you run without configuration?

The error you're encountering means that the app is failing to load a monspace font and so is falling back to a variable spaced font which causes problems. Turning off the guifont setting causes it to try to load the embedded font which fails for some reason.

Can you also run with --log and upload the log file?

**Comment by kiuKisas** [comment] 2020-03-18 18:05
I also have the mouse clicking offset again, log file:
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4350569/neovide_rCURRENT.log)

**Comment by Kethku** [comment] 2020-03-18 19:15
The log says that your system is using a font called "DankMono"
TRACE [neovide::renderer::caching_shaper] Font changed Some("DankMono") Some(15.0). It appears that dank mono doesn't report consistent spacing. Are you sure you removed all guifont calls from your config?

And can you try running with no config to see if the issue is specific to your vim init scripts?

**Comment by TheConfuZzledDude** [comment] 2020-03-18 20:01
Running with `neovide --log -u NONE` gives

[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/4351134/neovide_rCURRENT.log)

**Comment by Kethku** [comment] 2020-03-18 20:10
What does it look like in editor with no configuration. Does the error still repro?

**Comment by TheConfuZzledDude** [comment] 2020-03-19 18:41
Same as before with no config... I'll try building it manually just in case there's something wrong with the AUR package
![image](https://user-images.githubusercontent.com/3160203/77102680-21116d80-6a11-11ea-86f3-623ad73b277d.png)

**Comment by SirJson** [comment] 2020-03-27 18:56
I don't know if this is related to this issue but I'm found something similar.

If I set `guifont` to something that is not on my PC neovide renders text like this:
![fontok](https://user-images.githubusercontent.com/1042414/77790229-c1484180-7064-11ea-9c3b-d29a6e9d0c86.png)
This is looking fine but if I unset `guifont` this happens:
![fontweird](https://user-images.githubusercontent.com/1042414/77790293-de7d1000-7064-11ea-839c-77d05658b42b.png)

**Comment by Kethku** [comment] 2020-04-03 23:17
That is very distressing... These issues are part of why I want to roll our own font renderer. We can be sure these issues don't come up. As is we depend on skia and skribo to line up and it seems like they frequently dont

**Comment by TheConfuZzledDude** [comment] 2020-04-05 16:19
That sounds like a lot of extra work that would have to be done?

**Comment by SirJson** [comment] 2020-04-05 16:39
I kinda agree with @TheConfuZzledDude is there no way to work together with upstream? I remember implementing font rendering for my games back then and it was always like: Getting chars on the screen is easy but getting them right with layout and kerning and what not... not so much. But maybe I just sucked at using freetype2 :sweat_smile:

**Comment by Kethku** [comment] 2020-04-06 16:31
I think the difference for me is that we don't have to do all of the complicated bits of kerning and layout since neovim only works with fixed width fonts. You're right that its complicated, but the above issues are due to the font rendering capabilities in skulpin being necessarily not fixed width.

The caching font shaper https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs is all about this issue and about caching the results of shaped text which is a ton of wasted work if the glyphs are just rendered on a grid anyways.

All that said, I am coming around to your way of thinking that the surface area of neovide is already too big. I'm realizing that your point is right on the money that reducing the number of moving parts in favor of simpler architecture is nearly always a better strategy.

**Comment by kiuKisas** [comment] 2020-12-29 13:25
what about this: https://github.com/raphlinus/font-rs ? Also, why neovide doesn't use harfbuzz ?
I'm a bit confuse with all this things about font rendering, I'll appreciate a clarification about this if you have time.

**Comment by Kethku** [comment] 2020-12-30 01:23
Neovide does use harfbuzz under the covers in the caching shaper referenced above. For rendering neovide relies upon skia to take the positions from harfbuzz, place them, and then render them into text on the screen.

At this point I think most of these ligature issues dont' show up anymore, or if they do they are more related to font fallback/selection than actual rendering of the ligatures.

I could be wrong though!

**Comment by kiuKisas** [comment] 2021-01-04 14:56
Using `dankMono`, I still have issue with ligature. I don't have the latest update of the font so it can be an issue with the font itself.
See the screenshot below,
- second '`' missing with no text between, I assume it's due to ligature issue. It was happening more often before, the screenshot below is from the latest version on main branch (previously on neovide-git on arch linux, doesn't seems to be updated from a while ?).
- `-->` not render correctly

![image](https://user-images.githubusercontent.com/12698940/103546651-9f0d0b00-4ea3-11eb-9158-fe7e4552fbde.png)

**Comment by atomdmac** [comment] 2021-04-22 15:50
I'm not 100% sure if this is related or not but I'm trying to use the `Hasklug NF` nerd font and I'm seeing this:

### Before
![image](https://user-images.githubusercontent.com/1461736/115744497-9cee8f80-a360-11eb-9e66-064fa06e8151.png)

### After
![image](https://user-images.githubusercontent.com/1461736/115744589-b1cb2300-a360-11eb-8221-32d7b1fc1536.png)

Other non-nerd-font typefaces work fine (though obviously I can't use ligatures or icons).

The full log from `neovide --log -u NONE` can be found [here](https://pastebin.com/Y1P3H2j7)

One bit that seemed like it might be of interest:

```
TRACE [neovide::renderer::fonts::caching_shaper] Font changed: FontOptions { previous_guifont_setting: Some("Hasklug NF:w25"), fallback_list: ["Hasklug NF"], size: 14.0 }
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include embed-fonts feature
WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include embed-fonts feature
```

**Comment by PyGamer0** [comment] 2021-05-31 07:01
@atomdmac which version of neovide is that?

**Comment by atomdmac** [comment] 2021-06-01 13:07
@PyGamer0 The screenshots above were generated using `0.5.0`

**Comment by atomdmac** [comment] 2021-06-07 16:00
@PyGamer0 Looks to be fixed in `opengl` branch 🎊

**Comment by Kethku** [comment] 2021-06-13 23:49
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.

**Closed by Kethku** 2021-06-13 23:49 UTC
Labels: Font Fallback, bug
