### ISSUE TITLE
Very slow start on modern hardware

### ISSUE THREAD

**Issue by jurisbu** [Kethku/neovide#493] opened 2021-03-09 10:31 UTC
Just installed neovide v0.7.0-1 from AUR on Manjaro. The startup time is 4-5 seconds, which is really a no-go for me. And this is on Intel i7 (10th Gen) laptop. Otherwise than slow start this looks awesome. But again this slow start make my workflow of quickly spawning nvim instances quite painful.

**Comment by Kethku** [comment] 2021-03-11 07:14
I think this is due to font loading. I'm working on a change that might fix this, but it may be a bit.

**Comment by jurisbu** [comment] 2021-03-16 10:06
@Kethku Is there any way I can check that it is indeed due to font loading? Thanks!

**Comment by Dominux** [comment] 2021-04-14 12:37
I'm in a similar trouble in *Kubuntu 20.04*:

with *Intel i5 (8th Gen)*, *8 GB RAM* and *Nvidia GeForce MX230* (Yes, I don't possess so modern hardware, but I'm sure a lot of people will say that it's pretty enough to work with and I'll be agree with them), and ofc I'm not sure if my nvidia drivers work fine or at least work somehow (rather sure that that's negative)

Whatever it is, I've got my *Nvim* opening lesser than a second (dunno how long it takes, but it's just like opening a lot of programs. it's just quick enough to not even regard this as a bit slow), when *Neovide* opens it's window in **~20 seconds**, but this window is transparent like you can see in the picture below 
![image](https://user-images.githubusercontent.com/55978340/114709793-ad39b580-9d35-11eb-99ba-3f24b85d04ab.png)

After that it's completely starts after another 20 seconds. All time slots were taken by me approximetely, but the main point is that **Neovide takes totally ~40 seconds to open**

P.s.: Also I don't know what to do with this traceback of warnings and errors you can see in the picture above, but they appears in a first second right after submitting the key "neovide" in the terminal, may this be the cause of the trouble? Maybe I didn't create any required config yet (but I just went through whole readme and there wasn't one, so I don't think if it should be that way)

**Comment by jonpalmisc** [comment] 2021-05-05 03:27
I'm experiencing this too. I really hope this gets fixed soon, as Neovide looks quite cool and I'd like to use it.

**Comment by Kethku** [comment] 2021-05-26 01:00
Can you try the opengl branch? I think it may be faster there

**Comment by PyGamer0** [comment] 2021-06-22 13:05
@jurisbu @Dominux @jonpalmisc can you try building from `main` or grabbing a release from [here](https://github.com/Kethku/neovide/actions/runs/959962373).

**Comment by jurisbu** [comment] 2021-06-28 12:17
Happy to report that neovide starts pretty much instantly when build from `main` branch, commit bc1009b.

Followed instructions for Arch:
```
git clone https://aur.archlinux.org/neovide-git.git
cd neovide-git
nvim PKGBUILD
:%s/l}/l}#branch=main/
:wq
makepkg -si
```

**Comment by Kethku** [comment] 2021-06-30 01:12
Thats wonderful to hear. I'm curious which of the changes that went in fixed this problem...

**Comment by Kethku** [comment] 2021-06-30 01:12
In the meantime I'm closing this issue, but will be notified if you respond.

**Closed by Kethku** 2021-06-30 01:12 UTC
Labels: bug

**Comment by ZeusThundr** [comment] 2021-07-02 05:46
Followed the same steps as @jurisbu still slow for me
