### ISSUE TITLE
Scroll affecting fonts

### ISSUE THREAD

**Issue by atidyshirt** [Kethku/neovide#552] opened 2021-04-13 07:31 UTC
I am not entirely sure what is causing this, but when I scroll it causes the font to kind of dim out

using the following configuration
```
set guifont=FiraCode\ Nerd\ Font\ Mono:h14:style=Medium,Regular
```

https://user-images.githubusercontent.com/20514752/114513933-d5220e00-9c8e-11eb-94c8-c4519fbd4531.mp4

**Comment by Kethku** [comment] 2021-04-14 04:21
Maybe I'm totally blind... Can you point out more specifically what the issue is? Seems like you have a bunch of configuration that may be obscuring the problem for me.

**Comment by atidyshirt** [comment] 2021-04-14 04:35
@Kethku, the problem is related to #548 

it appears to be doing the same on my system except to a less noticeable extent and only after scrolling

in the video notice the font above gets dimmer and jagged

**Comment by Kethku** [comment] 2021-04-19 22:07
Ok I think I'm going to close this as a repeat of https://github.com/Kethku/neovide/issues/537 where I have consolidated those issues.

Do you know do you have dpi scaling enabled?

**Closed by Kethku** 2021-04-19 22:07 UTC
Labels: bug
