### ISSUE TITLE
utf8 character not correct with release 0.6

### ISSUE THREAD

**Issue by aj3423** [Kethku/neovide#280] opened 2020-05-08 08:50 UTC
Hi,  old 0.5 works fine  with "ttf-unifont" installed, but after update to 0.6.0, Chinese characters not displayed correctly, English characters works fine.

I tried the prebuilt package, and build myself, no difference.
How to fix?

![font](https://user-images.githubusercontent.com/4710875/81389169-feb3ea80-914b-11ea-9f43-e8e114b13213.png)

**Comment by jamespotz** [comment] 2020-05-08 14:40
Do you have `Noto Sans Mono` font installed ? if not try installing it using `sudo apt install fonts-noto-mono`

**Comment by aj3423** [comment] 2020-05-08 14:43
@jamespotz Yes, I have `Noto Sans Mono` installed.
```
fonts-noto-mono is already the newest version (20200323-1).
```

**Comment by jamespotz** [comment] 2020-05-08 15:13
@aj3423 try my branch if it fixes your issue
[https://github.com/jamespotz/neovide/tree/280-utf8-character-bug](https://github.com/jamespotz/neovide/tree/280-utf8-character-bug)

**Comment by aj3423** [comment] 2020-05-08 15:32
@jamespotz This branch doesn't work either..

**Comment by jamespotz** [comment] 2020-05-08 15:41
Do you still have the Unifont installed? And can you share the symbols used

**Comment by jamespotz** [comment] 2020-05-08 15:45
After reverting it back to unifont, I got the Chinese characters to render
![image](https://user-images.githubusercontent.com/4239625/81422717-f082c000-9185-11ea-84cf-e87c6612d2ef.png)

**Comment by aj3423** [comment] 2020-05-08 15:54
@jamespotz Yes, the `set guifont=Unifont` works, Chinese characters shows correctly.  But the Unifont  looks ugly. I was using 'Fira Code' which works fine with previous version 0.5.0, but not with  0.6.0.

**Comment by jamespotz** [comment] 2020-05-08 15:57
You dont have to set guifont to unifont, as long as you have unifont installed it will load it.

**Comment by aj3423** [comment] 2020-05-08 16:01
@jamespotz If I don't set any font (remove the vimrc), it looks like
![neovide square](https://user-images.githubusercontent.com/4710875/81424284-46f0fe00-9188-11ea-8d66-f6dd146af4d0.png)

**Comment by jamespotz** [comment] 2020-05-09 00:34
@aj3423 Your OS is kali right?

**Comment by aj3423** [comment] 2020-05-09 00:35
@jamespotz Yes. kali linux.

**Comment by jamespotz** [comment] 2020-05-09 00:36
Alright, Ill try to reproduce the problem in kali

**Comment by geekjam** [comment] 2020-05-09 05:31
Windows have same problem, Chinese not display correct after version 0.5

**Comment by Kethku** [comment] 2020-05-11 07:05
@geekjam this is a separate issue. Try adding a font which contains your characters to your guifont setting by separating font names with commas. Respond here if you continue to have issues.

**Comment by geekjam** [comment] 2020-05-11 12:27
@Kethku find out why, in new version, won't use system fonts for Chinese display, and so, some programming fonts will not work, like "Fira Code".

**Comment by Kethku** [comment] 2020-05-12 03:56
You can put multiple fonts separated by commas in the guifont. 

In the new version we stopped embedding fonts into the executable because it was causing too much of a performance cost. If you have a font with the characters you want you should specify it in the guifont setting

**Comment by geekjam** [comment] 2020-05-13 02:48
@Kethku looks like when use separated, only use the first font and doesn't mix
Like:
set guifont=FiraCode\ NF,宋体:h13
OR:
set guifont=宋体,FiraCode\ NF:h13

![1](https://user-images.githubusercontent.com/5414233/81765746-397ca080-9507-11ea-8b30-f037f28b28dc.png)

![2](https://user-images.githubusercontent.com/5414233/81765753-3d102780-9507-11ea-860f-cee01bffe89c.png)

**Comment by Kethku** [comment] 2021-01-11 09:55
closing in favor of https://github.com/Kethku/neovide/issues/444

**Closed by Kethku** 2021-01-11 09:55 UTC
Labels: Font Fallback
