### ISSUE TITLE
[Arch Linux] thread 'tokio-runtime-worker' panicked at boot time

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#139] opened 2020-02-18 08:54 UTC
I have this error when I launch neovide on my system:

`thread 'tokio-runtime-worker' panicked at 'Could not setup setting notifier for no_idle: Error processing request: 0 - 'Invalid method: nvim_exec')', src/error_handling.rs:5:5`

However, I can use neovide.

Distro: Arch Linux
Kernel: 5.5.4
NVIM v0.4.3
Neovide: last `Master` and `SDL2` branch

**Comment by Kethku** [comment] 2020-02-18 18:37
This is an issue for how the settings notifications work. I'm very confused how this could possibly happen as nvim_exec was introduced on 0.4.3. Can you send me the exact results of the version call in neovim?

**Comment by kiuKisas** [comment] 2020-02-18 20:37
```
❯ nvim -v
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by Kethku** [comment] 2020-02-18 20:56
can you actually call version inside of neovide? nvim -v could be different from the neovim install neovide finds

**Comment by Kethku** [comment] 2020-02-18 20:57
Probably unlikely, but would be useful

**Comment by Kethku** [comment] 2020-02-18 20:58
you can do it by calling the version ex command

```
:version<CR>
```

**Comment by kiuKisas** [comment] 2020-02-19 08:55
Same neovim version
![2020-02-19-095242_1920x1080_scrot](https://user-images.githubusercontent.com/12698940/74817839-e1664180-52fd-11ea-929b-4b40fbd77d5c.png)

**Comment by TristanCrawford** [comment] 2020-02-19 17:56
Looks similar to the issues I was running into.

Without RUST_BACKTRACE=1
> thread 'tokio-runtime-worker' panicked at 'Could not setup setting notifier for refresh_rate: Error processing request: 0 - 'Invalid method: nvim_exec')', src/error_handling.rs:5:5

This one seems like to be the only important one:
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/renderer/caching_shaper.rs:160:25

With RUST_BACKTRACE=1
> thread 'tokio-runtime-worker' panicked at 'Could not setup setting notifier for no_idle: Error processing request: 0 - 'Invalid method: nvim_exec')', src/error_handling.rs:5:5

Seems to be something to do with the font asset loading. I installed the fonts system-wide and it spun up just fine.

https://github.com/Kethku/neovide/blob/1f0d93ca3fce5b1fcafccc6bc81bbe0da206a6f2/src/renderer/caching_shaper.rs#L12-L17

https://github.com/Kethku/neovide/blob/1f0d93ca3fce5b1fcafccc6bc81bbe0da206a6f2/src/renderer/caching_shaper.rs#L25-L26

**Comment by Kethku** [comment] 2020-02-19 18:00
These are two separate issues. The nvim_exec error is definitely strange but the editor should still work. The font loading one is catastrophic. @TristanCrawford could you make a new issue with the font loading details?

**Comment by svermeulen** [comment] 2020-02-20 02:04
I'm getting this same error on startup on OSX 10.14.6 (also using nvim 0.4.3)

**Comment by TristanCrawford** [comment] 2020-02-21 01:10
The issue is that the latest "stable" release of neovim doesn't have `nvim_exec` in the API, it's in master and will be in 0.4.3 whenever it gets released. I wrote a small workaround if you'd like me to make a PR @Kethku?

**Closed** 2020-02-21 01:53 UTC
Labels: bug
