### ISSUE TITLE
Debian 10: VkError(ERROR_EXTENSION_NOT_PRESENT)

### ISSUE THREAD

**Issue by christophedh** [Kethku/neovide#627] opened 2021-05-04 21:02 UTC
Hi i got this error when i try to run the bin after compilation:

Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:456:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Debian 10
NVIM v0.5.0-dev+1259-gfe808f02f

thank your :)

**Comment by j4qfrost** [comment] 2021-05-06 08:51
Duplicate of https://github.com/Kethku/neovide/issues/579

**Closed by j4qfrost** 2021-05-06 08:51 UTC
