### ISSUE TITLE
Incorrect keycaptures

### ISSUE THREAD

**Issue by kilpkonn** [Kethku/neovide#759] opened 2021-06-26 08:36 UTC
**Description**
Some keybinding seem to be not working with neovide and some have wrong effects.
Problems:
- Switching between panes in `xmonad` inputs text to neovide (when switching back to neovide pane whilst in insert mode). Text entered: `<D-2><D-1>`. The switching is done with `Super+nr` so I supposed neovide captures these key presses whilst terminal does not. `<D-2>` is switching to pane 2 and <D-1> is switching back to pane where neovide is eg pane 1.
- `Ctrl+Shift+V` paste from system keyboard seems to be not working. It only enters `^` or `V` (it cycles between them eg pressing compo 2 times in a row becomes `^V`)
- After switching panes (the issue above) exiting insert mode with `Esc` duplicates line n times. The amount of times seems to be different every time but I suspect it is dependent on amount of time `Esc` held down. **NB: I have CAPS and ESC swapped wit setxkbmap, so I am pressing CAPS on physical keyboard**. It happens in a way that first `Esc` press does nothing and second press duplicates. It might be that this gets solved if the issue above is solved...

**Screenshots**
![image](https://user-images.githubusercontent.com/19900308/123507200-dd280200-d670-11eb-8d24-160859887750.png)
Line 1 is me switching between panes when in insert mode.  
Line 2 is me trying to paste with `Ctrl+Shift+V` in insert mode and then exit inset mode.
Next I wrote `aaa`, then switched between panes and then tried to exit insert mode causing this repetition.

**Desktop:**
![image](https://user-images.githubusercontent.com/19900308/123507373-a9011100-d671-11eb-86e1-8f875ec3027c.png)

**Please run `neovide --log` and paste the results here:**

```text
neovide --log
Ignored client type property: "methods"
Ignored client type property: "attributes"
```

**Additional context**
I noticed the repetition bug didn't happen when running neovide from terminal, but it does when I run it from `dmenu`. Pretty sure it's not a issue with `dmenu` / `xmonad` as everything works fine in terminal `nvim`.  
Also I have `en` keyboard map

**Comment by Kethku** [comment] 2021-06-26 23:19
Issue 1 is fixed in main. Please test it
Issue 2 is not a bug. Terminal nvim displays the same behavior. I believe this is a feature of your terminal emulator and is out of scope
Issue 3 I thiiink may be a subset of the issue 1. Can you try main?

If these aren't fixed please reopen this issue.

**Closed by Kethku** 2021-06-26 23:19 UTC
Labels: bug
