### ISSUE TITLE
Cursor issues in terminal buffer

### ISSUE THREAD

**Issue by thabaptiser** [Kethku/neovide#205] opened 2020-03-19 04:41 UTC
When in the terminal buffer in terminal mode, the cursor is offset by a little bit, and shifts the character below it as well when moving the cursor around.

Exiting to normal mode leaves a space after the character that used to be before the cursor in insert mode. 

Here's a gif illustrating these issues:
![ezgif-2-ea7165587fdf](https://user-images.githubusercontent.com/1356741/77031847-0af7a480-6960-11ea-9610-11b4b39e78b8.gif)

**Comment by Kethku** [comment] 2020-03-19 04:46
When you type into a normal text buffer do you run into the same issue? What do you have guifont set to? Does it happen without any configuration?

**Comment by thabaptiser** [comment] 2020-03-19 05:05
> When you type into a normal text buffer do you run into the same issue? What do you have guifont set to? Does it happen without any configuration?

I don't have the same issue in a text buffer, and I haven't set anything for guifont. Also, that gif is from running `neovide --clean`, so no config.

**Comment by thabaptiser** [comment] 2020-03-19 05:15
Actually, setting guifont to `Lucida_Console:h11` solves the issue. The default font must have something wrong with it's spacing.

Not setting guifont, it seems that there is also a similar issue in the "command entry" part of the window (not sure what it's actually called). It seems spaces don't take up as much space as they should, which is not the case in the text buffer. Here's another gif detailing the issue:
![ezgif-2-f9a35fcb2580](https://user-images.githubusercontent.com/1356741/77033782-6bd5ab80-6965-11ea-8d75-500a364dcc02.gif)

**Comment by Kethku** [comment] 2020-03-20 19:33
What platform are you running on? Arch Linux?

**Comment by thabaptiser** [comment] 2020-03-27 20:25
> What platform are you running on? Arch Linux?

 Operating System: Ubuntu 19.10
 Kernel: Linux 5.3.0-42-generic

**Comment by glacambre** [comment] 2020-04-02 12:44
Can reproduce on Ubuntu 18.04+Linux 5.3.0+i3 4.14.1+nvim v0.5.0-384-ga2efc9cf8+neovide c78fb4a6794f2dcaa08be524e07a571deb18a6db. I don't need to be in a terminal/command line to reproduce, insert mode in a regular buffer also triggers this bug.
Setting `set guifont=monospace` also makes the issue disappear. I'm still noticing two issues that might be related, as they seem to have something to do with the way the size of glyphs is computed:
- Letters aren't separated by the same amount of space everywhere:
![screenshot_2020-04-02-14:34:50](https://user-images.githubusercontent.com/11534587/78250562-4feb1180-74f0-11ea-8575-dac30445788a.png)
- When dragging neovim's cursor with the mouse from line 0, col 0 to line 64, col 100, the cursor doesn't follow the mouse properly. When the mouse reaches y:64,x:100, neovim's cursor is only on y:43, x:66. This probably means that Neovide thinks the glyphs are bigger than they actually are?

**Comment by glacambre** [comment] 2020-04-02 15:13
Font dimensions are computed using metrics
https://github.com/Kethku/neovide/blob/c78fb4a6794f2dcaa08be524e07a571deb18a6db/src/renderer/caching_shaper.rs#L277-L279
Which are taken from the current font set:
https://github.com/Kethku/neovide/blob/c78fb4a6794f2dcaa08be524e07a571deb18a6db/src/renderer/caching_shaper.rs#L213-L214
Which is built out of FontCollections:
https://github.com/Kethku/neovide/blob/c78fb4a6794f2dcaa08be524e07a571deb18a6db/src/renderer/caching_shaper.rs#L151-L155
Provided by Skribo:
https://github.com/Kethku/neovide/blob/c78fb4a6794f2dcaa08be524e07a571deb18a6db/src/renderer/caching_shaper.rs#L11

But as far as I can tell, font shaping is actually done by Skia:
https://github.com/Kethku/neovide/blob/c78fb4a6794f2dcaa08be524e07a571deb18a6db/src/renderer/caching_shaper.rs#L237-L248

So perhaps there is a discrepancy between the way Skribo computes glyph size and the way Skia does it? Skia has its own font metrics:
https://docs.rs/skia-safe/0.17.0/skia_safe/font_metrics/struct.FontMetrics.html

What's odd is that while there does seem to be a way to retrieve the max width of the character set, there's no way to know the max height. Perhaps because self.base_size is the cell height?

**Comment by Kethku** [comment] 2021-06-22 08:46
These issues have been fixed in main.

**Closed by Kethku** 2021-06-22 08:46 UTC
Labels: bug
