### ISSUE TITLE
Fresh install panics on startup

### ISSUE THREAD

**Issue by Connor-Frank** [Kethku/neovide#610] opened 2021-04-29 22:30 UTC
I've successfully used Neovide in the past, but I reinstalled my system recently and Neovide didn't start successfully. After running with `RUST_BACKTRACE=full`, here's the output:

```
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create window: SdlError("Installed Vulkan doesn\'t implement the VK_KHR_surface extension")', src/window/sdl2/mod.rs:442:10
stack backtrace:
   0:     0x558f31403930 - <unknown>
   1:     0x558f3132a7bc - <unknown>
   2:     0x558f314031b1 - <unknown>
   3:     0x558f31402b55 - <unknown>
   4:     0x558f3140223a - <unknown>
   5:     0x558f31421508 - <unknown>
   6:     0x558f3142147c - <unknown>
   7:     0x558f3142142d - <unknown>
   8:     0x558f31328b20 - <unknown>
   9:     0x558f3132ed52 - <unknown>
  10:     0x558f312e5699 - <unknown>
  11:     0x558f312dcd06 - <unknown>
  12:     0x558f31269043 - <unknown>
  13:     0x558f312d93d5 - <unknown>
  14:     0x7f2b826f6b25 - __libc_start_main
  15:     0x558f3125877e - <unknown>
  16:                0x0 - <unknown>
```

**Comment by enderger** [comment] 2021-04-30 04:21
Possible duplicate of #607

**Comment by Lord-Valen** [comment] 2021-04-30 15:05
Looks like a Vulkan error. Did you try the OpenGL Branch?

**Comment by enderger** [comment] 2021-04-30 15:09
It looks like your Vulkan install is to blame, see https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/enabling_extensions.md

**Comment by enderger** [comment] 2021-04-30 15:22
Actually, duplicate of #209

**Comment by Kethku** [comment] 2021-04-30 18:13
@enderger would you be willing to adjust the readme to make this more obvious? I've been struggling to help with the vulkan driver issues because I am not a linux guy

**Comment by Connor-Frank** [comment] 2021-05-01 17:27
Thank you everyone. Sorry for the duplicate issue; I wasn't sure what the culprit was so I didn't know how to search through previous issues. Looking forward to using Neovide!

**Closed** 2021-05-03 21:17 UTC
Labels: Vulkan Driver, bug
