### ISSUE TITLE
[ Font Rendering ] thin separating line between the two font squares

### ISSUE THREAD

**Issue by NEX-S** [Kethku/neovide#2586] opened 2024-05-23 14:23 UTC
`vim.o.guifont = "JetBrainsMono Nerd Font Mono:h13"`

![Screenshot from 2024-05-23 22-19-55](https://github.com/neovide/neovide/assets/97107165/7c5e81ed-51f9-4842-8dc7-0c8ca5ccec3b)

There is a thin separating line between the two font squares and i dont know why this won't happen in my kitty terminal

**Comment by fredizzimo** [comment] 2024-05-23 14:30
I'm closing this as a duplicate of
* https://github.com/neovide/neovide/issues/2491

**Closed as completed by fredizzimo** 2024-05-23 14:30 UTC
Labels: bug
