### ISSUE TITLE
Emoji on Linux builds

### ISSUE THREAD

**Issue by PureFunctor** [Kethku/neovide#353] opened 2020-09-06 13:01 UTC
I've recently built Neovide from source, specifically from commit [6db2b50](https://github.com/Kethku/neovide/commit/6db2b50569e0e3021a800bd724bc936c57db231b) on Manjaro and I've noticed that emoji don't seem to appear, e.g. the output from `mutmut` on Neovide compared to XFCE Terminal.
![image](https://user-images.githubusercontent.com/66708316/92326235-51ae9780-f083-11ea-94c3-4e0010cc5253.png)
![image](https://user-images.githubusercontent.com/66708316/92326275-83276300-f083-11ea-9028-a6352684daa3.png)
Is there any way around this, or is it a current limitation?

**Comment by Kethku** [comment] 2020-09-07 00:20
You can specify font fallback by setting multiple font names in your guifont configuration. Missing characters in the first font will be filled from the second etc. This way you can specify a font containing the missing characters and have things work as expected

**Comment by PureFunctor** [comment] 2020-09-07 03:36
I've tried setting multiple fonts in my `guifont` configuration with the following setups:
[ttf-twemoji](https://aur.archlinux.org/packages/ttf-twemoji/) + `set guifont=FiraCode\ Nerd\ Font\ Mono,Twemoji`
[noto-fonts-emoji](https://www.archlinux.org/packages/extra/any/noto-fonts-emoji/) + `set guifont=FiraCode\ Nerd\ Font\ Mono,Noto\ Color\ Emoji`
[ttf-twemoji-color](https://aur.archlinux.org/packages/ttf-twemoji-color) + `set guifont=FiraCode\ Nerd\ Font\ Mono,Twitter\ Color\ Emoji`
I've had little success getting the first two to display as they only output invisible characters within Neovide, `ttf-twemoji-color` on the other hand just displays black and white wireframes of the emoji

**Comment by Kethku** [comment] 2020-09-07 18:56
I'm not sure what might be going wrong there at least in principle the system should use your the default emoji font of https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L36

**Comment by Kethku** [comment] 2020-09-07 18:56
Oh you're on linux. Nvm

**Comment by Kethku** [comment] 2020-09-07 18:57
Is it possible that the name is wrong somehow?

**Comment by PureFunctor** [comment] 2020-09-08 02:38
That doesn't seem to be the case, I've used `nvim-qt` to set the `guifont` using the graphical prompt and I was able to select `Noto Color Emoji` just fine:
![image](https://user-images.githubusercontent.com/66708316/92427410-fc77a080-f1be-11ea-880c-fe738e8cd325.png)
![image](https://user-images.githubusercontent.com/66708316/92427492-38ab0100-f1bf-11ea-94c1-232240ad2f3a.png)

The problem might be related to my `fontconfig` configuration but I'm not well-versed regarding that tool.

**Comment by Kethku** [comment] 2020-09-08 19:35
guifont's usage is... flexible. I believe the docs for it just suggest a format and that the format changes from gui to gui. How it works in neovim-qt could very well (and I believe is) be different from neovide.

**Comment by Kethku** [comment] 2020-09-08 19:37
@j4qfrost any chance the default font is screwing this up? I don't know how the fallback works. Does the specified fallback list get prepended, or does the fallback add the default system fonts (including the emoji one) and then append any user specified fallback to that list?

If its the latter, it could be that the system font selected is rendering strangely and that is responsible for the issue

**Comment by j4qfrost** [comment] 2020-09-08 19:43
I'll double check the ordering. The fallback was set to choose a random system font if no valid option was listed. Where are the emojis located?

**Comment by p00f** [comment] 2020-09-11 12:07
I can confirm this issue on my system (archlinux)

**Comment by p00f** [comment] 2020-09-11 12:19
> @j4qfrost any chance the default font is screwing this up? I don't know how the fallback works. Does the specified fallback list get prepended, or does the fallback add the default system fonts (including the emoji one) and then append any user specified fallback to that list?
> 
> If its the latter, it could be that the system font selected is rendering strangely and that is responsible for the issue

I think my system emoji font is also proper, my config - https://github.com/p00f/dotfiles/tree/main/fontconfig/.config/fontconfig/conf.d, which are the contents of my `~/.config/fontconfig/conf.d`

Emojis wouldn't work earlier in terminals because they had a lower priority, now they do

**Comment by p00f** [comment] 2020-09-11 16:10
Also, my `guifont` includes an emoji font, so this might not be a fallback issue at all (talking about the label)

**Comment by kitegi** [comment] 2020-09-25 00:15
it seems to work with EmojiOne instead of Noto Color Emoji, though the emojis aren't colored.

**Comment by Kethku** [comment] 2021-01-11 09:49
I'm closing this in favor of https://github.com/Kethku/neovide/issues/444

**Closed by Kethku** 2021-01-11 09:49 UTC
Labels: Font Fallback, bug
