### ISSUE TITLE
[Smooth Scrolling] Doesn't seems to work on Arch Linux

### ISSUE THREAD

**Issue by kiuKisas** [Kethku/neovide#433] opened 2021-01-04 16:02 UTC
Test on Arch linux with the latest version on the branch `main`, I can't see any difference when I scroll. 

https://user-images.githubusercontent.com/12698940/103553989-86eeb900-4eae-11eb-83c0-8596c400beb4.mp4

Did I miss something ?

**Comment by duvallj** [comment] 2021-01-04 19:04
Doesn't seem to be in the main branch yet, still in smooth-scrolling which should get merged soon according to #62

**Comment by kiuKisas** [comment] 2021-01-04 20:25
According to this commit https://github.com/Kethku/neovide/commit/1d981f3c2ce56d3c333a2d12fd0c4647119eeaa4 and this branch https://github.com/Kethku/neovide/pull/423, it was merged couple of days ago

**Comment by Kethku** [comment] 2021-01-05 00:13
@kiuKisas given your other issue, I assume you have multiGrid enabled in this gif?

@duvallj smooth scrolling has been merged but is locked behind a command line argument or environment variable. 
https://github.com/Kethku/neovide/wiki/Configuration#multiGrid

**Comment by duvallj** [comment] 2021-01-05 00:57
@Kethku weird, I thought I enabled multiGrid (with `target/release/neovide --multiGrid`) yet was able to reproduce this on Windows. I've tried using both the scroll wheel and j/k/arrow keys; is there an extra setting besides multiGrid that needs to be enabled?

**Comment by Kethku** [comment] 2021-01-05 00:59
Very strange. The effect is a little subtle. The scrolling isn't like most windows but rather animates the position of the scroll buffer into place. Its most visible when jumping to the start or end of a file (incidentally this is also where the limitations of the effect are highlighted most)

**Comment by duvallj** [comment] 2021-01-05 01:20
![2021-01-04-neovide-scrolling-smaller2](https://user-images.githubusercontent.com/10897431/103595713-240b1b00-4eca-11eb-8d4e-9264b8064515.gif)
Here is a (poor quality) screencap I took; the effect still wasn't noticeable when scrolling around like you describe.

**Comment by Kethku** [comment] 2021-01-05 01:22
Interesting. Are you sure that multigrid is working? Do windows animate around?

**Comment by duvallj** [comment] 2021-01-05 01:27
Resizing windows seems to be animated with the --multiGrid option, and not animated otherwise yes

**Comment by kiuKisas** [comment] 2021-01-05 09:57
@Kethku yes `--multiGrid` is enable (you can see it on the left of my gif). Same issue as @duvallj , windows are animated but no scroll animation; or not noticeable

**Comment by drzel** [comment] 2021-03-12 16:57
Same here, on Debian 11 (bullseye testing), launching with:

```
neovide --multiGrid
```
No smooth scroll.

**Comment by kiuKisas** [comment] 2021-03-19 09:37
Seems to be fixed in the latest build. Awesome ! :D

**Comment by Kethku** [comment] 2021-03-19 23:42
I'd be pleased if that were the case! But I'm not sure what would have fixed it...

**Comment by kiuKisas** [comment] 2021-03-20 18:31
https://user-images.githubusercontent.com/12698940/111881848-c65b7a80-89b2-11eb-9c72-1b6aa1494f33.mp4

**Comment by Kethku** [comment] 2021-03-21 03:08
Ok. I'm going to keep this open for a bit as I heard grumblings that other folks were having similar issues.

**Comment by p00f** [comment] 2021-04-05 07:38
I just built `main`, C-e/C-y scroll line-by-line
https://user-images.githubusercontent.com/36493671/113550027-04da7180-9610-11eb-967f-875c5b7ecbe5.mp4

**Comment by Kethku** [comment] 2021-04-05 17:49
@p00f maybe I'm blind. That gif looks correct to me. What am I missing?

**Comment by p00f** [comment] 2021-04-05 22:20
It scrolls one line at a time

**Comment by Kethku** [comment] 2021-04-07 22:58
Maybe the confusion comes from the gif on the main readme? That is using an extension to "smoothly jump lines" then the smooth scroll system interpolates those line jumps. The result is a larger jump that smoothly animates into place.

I use https://github.com/yuttie/comfortable-motion.vim to do the larger changes.

Maybe the readme is misleading and I should explain more?

**Comment by Kethku** [comment] 2021-04-07 22:59
In the gif you linked, you can see the system animate the single line jumps. And when you jump to the top or bottom of the document, those are animated as well

**Comment by p00f** [comment] 2021-04-07 23:43
Right, understood

**Comment by Kethku** [comment] 2021-05-26 00:58
I'm closing this as to my knowledge it is not fixed at the very least in the opengl branch

**Closed by Kethku** 2021-05-26 00:58 UTC
Labels: bug

**Comment by SanJacobs** [comment] 2022-08-07 18:33
I'm not sure what you meant by that last comment, but I thought I'd let you know that I've still got this issue on version 0.9.

As you can see in this video, most of the multigrid stuff is working. I get blurred popups and smooth window animations, but no smooth scrolling.

https://user-images.githubusercontent.com/21090839/183305763-1053b43a-6d4b-4318-af41-2e448886c949.mp4
