### ISSUE TITLE
Doesn't open. Arch.

### ISSUE THREAD

**Issue by qazip** [Kethku/neovide#626] opened 2021-05-04 15:12 UTC
```
> neovide   
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:456:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
neovide --version
Neovide version: 0.7.0
```

**Comment by RajPorus19** [comment] 2021-05-06 07:24
Add the following at the end of your .bashrc or similar : 
```
export RUST_BACKTRACE=1
export RUST_BACKTRACE=full
```

**Comment by j4qfrost** [comment] 2021-05-06 08:50
Duplicate of https://github.com/Kethku/neovide/issues/579



> Add the following at the end of your .bashrc or similar :
> 
> ```
> export RUST_BACKTRACE=1
> export RUST_BACKTRACE=full
> ```

@RajPorus19 The bottom line overwrites the top line.

**Closed by j4qfrost** 2021-05-06 08:50 UTC

**Comment by qazip** [comment] 2021-05-06 08:52
```
❯ neovide                 
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'Failed to create renderer: CreateInstanceError(InstanceError(VkError(ERROR_EXTENSION_NOT_PRESENT)))', src/window/sdl2/mod.rs:456:14
stack backtrace:
   0:     0x55a1185cf840 - <unknown>
   1:     0x55a1184f516c - <unknown>
   2:     0x55a1185cf0b1 - <unknown>
   3:     0x55a1185cea15 - <unknown>
   4:     0x55a1185ce0fa - <unknown>
   5:     0x55a1185ed5f8 - <unknown>
   6:     0x55a1185ed56c - <unknown>
   7:     0x55a1185ed51d - <unknown>
   8:     0x55a1184f34c0 - <unknown>
   9:     0x55a1184f9702 - <unknown>
  10:     0x55a1184c8e44 - <unknown>
  11:     0x55a1184b2c54 - <unknown>
  12:     0x55a118449213 - <unknown>
  13:     0x55a1184af345 - <unknown>
  14:     0x7f92620b9b25 - __libc_start_main
  15:     0x55a11841077e - <unknown>
  16:                0x0 - <unknown>
```
