### ISSUE TITLE
Only use dpi hack if on windows. Use drawing_size vs size on other platforms

### ISSUE THREAD

**Issue by alichtman** [Kethku/neovide#177] opened 2020-03-02 22:06 UTC
```
$ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
$sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020
```

```bash
cargo build --release
   Compiling objc_exception v0.1.2
   Compiling core-foundation-sys v0.7.0
   Compiling proc-macro2 v0.4.30
   Compiling arrayvec v0.4.12
error: failed to run custom build command for `objc_exception v0.1.2`

Caused by:
  process didn't exit successfully: `/Users/alichtman/open-source-software/neovide/target/release/build/objc_exception-fdd3de99a89a7e32/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = Some("/usr/local/bin/gcc-9")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
running: "/usr/local/bin/gcc-9" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/Users/alichtman/open-source-software/neovide/target/release/build/objc_exception-f297329db0d1e37c/out/extern/exception.o" "-c" "extern/exception.m"
cargo:warning=extern/exception.m: In function 'RustObjCExceptionThrow':
cargo:warning=extern/exception.m:5:5: error: '-fobjc-exceptions' is required to enable Objective-C exception syntax
cargo:warning=    5 |     @throw exception;
cargo:warning=      |     ^
cargo:warning=extern/exception.m:4:32: warning: parameter 'exception' set but not used [-Wunused-but-set-parameter]
cargo:warning=    4 | void RustObjCExceptionThrow(id exception) {
cargo:warning=      |                             ~~~^~~~~~~~~
exit code: 1

--- stderr


error occurred: Command "/usr/local/bin/gcc-9" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/Users/alichtman/open-source-software/neovide/target/release/build/objc_exception-f297329db0d1e37c/out/extern/exception.o" "-c" "extern/exception.m" with args "gcc-9" did not execute successfully (status code exit code: 1).
```

**Comment by Kethku** [comment] 2020-03-02 23:41
Maybe try just running from the build here: https://github.com/Kethku/neovide/actions/runs/48340097
I don't have a mac so I don't know what causes this.

A similar error reported here: https://github.com/rust-lang/rustup/issues/1908 suggests that you are missing an objective c compiler. I guess its needed for skribo?

**Comment by raguay** [comment] 2020-03-03 05:33
I tried your compiled version and I am getting this error running from the command line:

```
$ open /Applications/Neovide.app 
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Neovide.app.
```

I think that means the macOS security isn't allowing it to run. 

I was able to get it to compile by making sure my build chain was on the current nightly, open Xcode to install all of the components (just the command line install doesn't install some of the compilers needed), and then recompile. It is working, but very large letters! I have it set to 14pt font, but the display is more like 22pt. Are there in configs for this?

**Comment by Kethku** [comment] 2020-03-03 06:58
The dpi settings are a little wonky on Mac. glad it's working though! The font configs are done via the guifont variable in your vim config

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by raguay** [comment] 2020-03-03 07:24
But, that will change it for the terminal runs as well. I just need it
fixed on the Neotide load.

Also, it is a bit slow on responding to key movements. The animations are
lagging everything quit a bit. How can I get it to be more zippy?

**Comment by Kethku** [comment] 2020-03-03 07:56
I use this in my config 
```
let g:neovide_cursor_animation_length = 0.08
```

**Comment by raguay** [comment] 2020-03-03 08:36
Okay, that helped my animation. I changed my font, but the rendering is
still very large, but in my terminal, very small now.

**Comment by Kethku** [comment] 2020-03-03 08:40
The way I figured out to handle dpi settings is by querying the UI for what the current dpi is compared to the expected dpi for the given platform. https://github.com/Kethku/skulpin/blob/sdl2/src/renderer/mod.rs#L45

I read somewhere that the expected value should be 72 for macos. But maybe thats wrong?

In any case, neovide declares a neovide global variable on startup with a value of v:true. So you could check for that in your config and set the guifont accordingly at least until we fix the dpi stuff for real.

**Comment by raguay** [comment] 2020-03-03 08:49
BTW: Since I'm now launching from command line, I'm getting these errors:
```
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed
488185134
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open
```
Not sure if this is relevant or not.

**Comment by raguay** [comment] 2020-03-03 08:52
The dpi will be different for different macs. I don't have the really high
res screens like a macbook Pro. I'm using a macBook Air.

No matter what I change the font to, it is still showing very large. I've
taken it down to 8 and it's still big.

**Comment by Kethku** [comment] 2020-03-03 08:52
Yes the dpi is different, but the expected dpi is constant. The ratio between the two gives the desired scaling

**Comment by hello2dj** [comment] 2020-03-03 13:22
same macos version, rustc: 1.40 build failed
   
Compiling sdl2-sys v0.33.0 (https://github.com/Rust-SDL2/rust-sdl2#4e81db58)
error: failed to run custom build command for `sdl2-sys v0.33.0 (https://github.com/Rust-SDL2/rust-sdl2#4e81db58)`

Caused by:
  process didn't exit successfully: `/Users/dengjie/Study/rust/neovide/target/debug/build/sdl2-sys-94abb6b51963db17/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: TarError { desc: "failed to unpack `/Users/dengjie/Study/rust/neovide/target/debug/build/sdl2-sys-de836d795a5d676f/out/SDL2-2.0.10/Xcode/SDL/pkg-support/sdl_logo.pdf`", io: Custom { kind: InvalidInput, error: TarError { desc: "failed to unpack `SDL2-2.0.10/Xcode/SDL/pkg-support/sdl_logo.pdf` into `/Users/dengjie/Study/rust/neovide/target/debug/build/sdl2-sys-de836d795a5d676f/out/SDL2-2.0.10/Xcode/SDL/pkg-support/sdl_logo.pdf`", io: Custom { kind: InvalidInput, error: "corrupt deflate stream" } } } } }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by hello2dj** [comment] 2020-03-03 13:26
macos: 10.14.6, rustc: 1.40.0 build failed 
Compiling sdl2-sys v0.33.0 (https://github.com/Rust-SDL2/rust-sdl2#4e81db58)
    Building [====================================================>  ] 268/274: sdl2-sys(build)
error: failed to run custom build command for `sdl2-sys v0.33.0 (https://github.com/Rust-SDL2/rust-sdl2#4e81db58)`

Caused by:
  process didn't exit successfully: `/Users/dengjie/Study/rust/neovide/target/debug/build/sdl2-sys-94abb6b51963db17/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: TarError { desc: "failed to unpack `/Users/dengjie/Study/rust/neovide/target/debug/build/sdl2-sys-de836d795a5d676f/out/SDL2-2.0.10/Xcode/SDL/pkg-support/sdl_logo.pdf`", io: Custom { kind: InvalidInput, error: TarError { desc: "failed to unpack `SDL2-2.0.10/Xcode/SDL/pkg-support/sdl_logo.pdf` into `/Users/dengjie/Study/rust/neovide/target/debug/build/sdl2-sys-de836d795a5d676f/out/SDL2-2.0.10/Xcode/SDL/pkg-support/sdl_logo.pdf`", io: Custom { kind: InvalidInput, error: "corrupt deflate stream" } } } } }', src/libcore/result.rs:1165:5
stack backtrace:

**Comment by Kethku** [comment] 2020-03-03 15:44
@hello2dj that is a different build issue. Please create a new issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment] 2020-03-03 15:45
I deleted it to keep context clean. (Not trying to be mean)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kethku** [comment] 2020-03-07 05:40
Window size issue should be fixed. @raguay can you try?

**Comment by raguay** [comment] 2020-03-07 13:02
I've tried it and it is still very large. But, I can't get any of my vim
based programs to change their fonts right now.

**Comment by Kethku** [comment] 2020-03-07 22:55
Interesting what is your guifont setting in your vim config?

**Comment by Kethku** [comment] 2020-03-08 00:01
@raguay I just realized that my update didn't actually work. It should be working now. Can you try again?

**Comment by raguay** [comment] 2020-03-08 07:07
Okay. that fixed the issue for me. Thanks.

**Closed** 2020-03-08 07:08 UTC
Labels: bug, waiting
