### ISSUE TITLE
Wierd Artifacting and broken fonts after scrolling

### ISSUE THREAD

**Issue by smit2909** [Kethku/neovide#755] opened 2021-06-25 19:52 UTC
**Describe the bug**

- On scrolling through files, weird artefacts, like colour from status line remains persistent
- The fonts become completely illegible blurry

**To Reproduce**
1. Go to Terimal, open any file in neovide
2. Scroll down using j or shift + ] or any other key
3. See error

**Expected behavior**
Fonts and lines should not be cut off after scrolling

**Screenshots**
![Screenshot from 2021-06-26 01-08-56](https://user-images.githubusercontent.com/79797111/123477815-387bd500-d61c-11eb-9222-d443b4e2876b.png)
![Screenshot from 2021-06-26 01-09-11](https://user-images.githubusercontent.com/79797111/123477845-4893b480-d61c-11eb-9d13-7d67478b7a1b.png)

Look at line 210 in below screenshot
![Screenshot from 2021-06-26 01-07-33](https://user-images.githubusercontent.com/79797111/123477907-5c3f1b00-d61c-11eb-94dd-ebed75667321.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.10], using xmonad
 - Neovide Version: latest commit from master
 - Neovim Version 0.5

**Comment by Kethku** [comment] 2021-06-25 20:22
What font are you using

**Comment by smit2909** [comment] 2021-06-26 02:27
Here a bunch that very consistently show such behaviour

- FiraCode Nerd Font
- Sauce Code Pro
- Jetbrains Mono
- Cascadia Code PL
- Ubuntu Mono / Nerd Font

**Comment by doums** [comment] 2021-06-29 22:14
Hi, I observe the same bug here.

- Arch Linux
- Neovide 0.7.0
- neovim (build myself)
```
NVIM v0.5.0-dev+1450-g5aaa1a1c0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Kethku** [comment] 2021-07-01 22:25
i can repro something like this on windows now. The trick was dpi scaling had to be enabled, so it looks like this has to do with the renderer's interaction with scaling.

**Comment by last-partizan** [comment] 2021-07-03 13:24
Yes, it seems related to scaling. I tried to reproduce bug with scaling set to 1, and was not able to. At 1 it works fine.

When using wayland it renders at 1 regardless of system-wide scaling.

I'll try to dig this issue.

**Comment by doums** [comment] 2021-07-03 13:56
What scaling setting are you talking about ?

**Comment by last-partizan** [comment] 2021-07-03 14:07
I'm talking about this scaling: https://docs.rs/winit/0.22.2/winit/window/struct.Window.html#method.scale_factor

If you're using x11, it's calculated from DPI.

**Comment by last-partizan** [comment] 2021-07-03 17:27
As workaround you can set `WINIT_X11_SCALE_FACTOR=1` and just set bigger font size.

**Comment by last-partizan** [comment] 2021-07-03 18:51
@doums try running latest version with `neovide --log`, and then show me `grep scale neovide_rCURRENT.log`. And what exact font and font size are you using?

Issue is affecting some font sizes more than others, and i want to find some good combinations to reproduce it.

**Comment by last-partizan** [comment] 2021-07-03 18:55
@Kethku I'm pretty sure it's some sort of rounding issue. `window.scale_factor()` sometimes passed as f64 and sometimes as f32. And multiplied by font size in some parts. And with scaling like 1 or 2 it works perfectly fine.

Maybe you have some ideas/hints?

**Comment by last-partizan** [comment] 2021-07-03 21:13
@Kethku i'm worried abount those lines:

![image](https://user-images.githubusercontent.com/301015/124366308-6b931980-dc57-11eb-8714-3d81b2d0e185.png)

In `src/renderer/mod.rs:draw_frame` there is `root_canvas.scale((scaling, scaling));`
And in `src/renderer/rendered_window.rs:handle_window_draw_command` there is `canvas.scale((scaling, scaling));`

If i comment out one of them, it scales in half, if i comment both - it scales in half more. Is it supposed to work this way?

**Comment by last-partizan** [comment] 2021-07-04 21:03
When i get these artifacts, cursor is rendered at slightly different (and i think, **correct**?) position.

![image](https://user-images.githubusercontent.com/301015/124399384-c5f9ac00-dd23-11eb-9bc5-e6397ac3c299.png)

And when i change mode to visual and make a selection, line gets rerendered at same position as cursor, without artifacts.

**Comment by Kethku** [comment] 2021-07-05 00:00
I introduced a fix for this here: https://github.com/Kethku/neovide/pull/791 which removes the scroll performance optimization which seems to cause the issue. Could you try it and or review the change? I know you've been looking into this @last-partizan

**Comment by last-partizan** [comment] 2021-07-05 20:46
https://github.com/Kethku/neovide/pull/793

Here is another fix. @doums @smit2909 please, try it.

**Comment by doums** [comment] 2021-07-06 07:38
bug seems to be fixed in #793 good job !

But I can't build main, it's failing with
```
error: checksum for `skia-safe v0.40.2` changed between lock files
```

**Comment by last-partizan** [comment] 2021-07-06 07:40
@doums Merged fix

**Comment by doums** [comment] 2021-07-06 07:52
main is still broken

**Comment by smit2909** [comment] 2021-07-06 08:06
> #793
> 
> Here is another fix. @doums @smit2909 please, try it.

Awsome! Working like a charm @last-partizan . No more broken fonts. I am on 755-scale-factor branch though. I didnt build after the merge into main.

**Comment by last-partizan** [comment] 2021-07-06 08:07
@doums are you sure?

https://github.com/Kethku/neovide/commit/5c5cf9088da9ce205f2225ca969fcf2f251e4c12

Does `git log` includes this commit?

**Comment by last-partizan** [comment] 2021-07-06 08:08
Just to be clear, #793 is not merged yet.

I just merged fixes for broken main branch.

**Comment by doums** [comment] 2021-07-06 08:20
> @doums are you sure?
> 
> [5c5cf90](https://github.com/Kethku/neovide/commit/5c5cf9088da9ce205f2225ca969fcf2f251e4c12)
> 
> Does `git log` includes this commit?

I was talking about artifact bug on main branch. Yes the build is fixed of main branch and yes it includes the commit.

**Comment by last-partizan** [comment] 2021-07-07 06:11
This should be fixed now on main.

**Closed by last-partizan** 2021-07-07 06:11 UTC
Labels: bug
