### ISSUE TITLE
Linux OpenGL: Some keys and Shift+key combinations not working

### ISSUE THREAD

**Issue by mikkovedru** [Kethku/neovide#691] opened 2021-05-27 20:10 UTC
Unlike the 3-point list mentioned in #655, there are a couple of other issues remaining. One of which is that some of the keys and Shift+key combinations are not working.

## Technical background
- Linux Mint 20.1 Cinnamon (4.8.6), based on Ubuntu 20.04
- Kernel 5.8.0-53-generic
- GeForce GTX 650, Nvidia drivers 390
- X, OpenGL (I successfully converted the Vulkan version, but was not able to run it).
- I am using a [Finnish (Scandinavian) keyboard layout](http://kbdlayout.info/KBDFI/) with my own changes. 

## Details about the bug
- Shift+1 (`!`) is not working
- Shift+2 (`"`) is not working
- Shift+3 (`#`) is not working
- Shift+. (`:`) is working
- Shift+, (`;`) is giving `:` instead
- `<` and `>` are not working
- Scandinavian `ö`, `ä`, `å` are not working
- Shift+7 (`/`) is giving `?` instead

I could go on and on with examples.

**Comment by Kethku** [comment] 2021-05-27 21:57
Until the PRs outlined in https://github.com/Kethku/neovide/issues/445 are resolved, the way to fix this is to introduce a keyboard layout similar to this one: https://github.com/Kethku/neovide/blob/opengl/src/window/window_wrapper/layouts/qwerty.rs for your layout and then configure it in your vim config.

I'd be happy to take a PR for this! I'm very hopeful though that the upstream changes will merge in the not overly distant future... but its hard to know when that will happen

**Comment by Kethku** [comment] 2021-05-27 21:59
I'm inclined to close this as repeat of #445 but I'm gonna leave it open for further discussion just in case

**Comment by meluskyc** [comment] 2021-05-28 03:59
This might be unrelated, but strangely some shift+keys can't be mapped.

e.g. these do not work. Windows 10 Qwerty en-us. 

```
imap ! a
imap ) b
```

**Comment by valignatev** [comment] 2021-05-30 04:06
I have the same problem, my kb is just a regular qwerty ansi. Only happens on opengl branch. Shift+1, open and closing parens are not working either.

**Comment by ergpopler** [comment] 2021-06-02 19:58
Is there any fix? 
I am on the latest opengl branch and I cannot use neovide!
shift+1 for example doesn't work. The only shift+* that works is shift+2 (@).
I am using a regular qwerty en-us keyboard.

**Comment by Kethku** [comment] 2021-06-02 20:40
I don't have a fix atm as I've been pushing on the font fallback and rendering issues in the opengl branch. I'm guessing that this is a relatively simple issue that has to do with the event handling from winit. Could somebody here take a look at that? The initial handling is here: https://github.com/Kethku/neovide/blob/main/src/window/winit/mod.rs#L109

I've been putting off pushing on it with the hope that the upstream PRs will merge, but its looking more like I'm going to figure out the remaining issues in opengl first, so this is bumping up in priority.

**Comment by Kethku** [comment] 2021-06-02 20:41
As a side note, I'm able to reproduce this issue in wslg so I think its pretty broad

**Comment by meluskyc** [comment] 2021-06-03 03:22
Not great. Looks like a winit issue on Linux. `virtual_keycode` is None for most Shift+# keys. 

```
[src/window/window_wrapper/mod.rs:308] &input = KeyboardInput {
    scancode: 10,
    state: Pressed,
    virtual_keycode: None,
    modifiers: SHIFT,
}
[src/window/window_wrapper/mod.rs:308] &input = KeyboardInput {
    scancode: 10,
    state: Released,
    virtual_keycode: None,
    modifiers: SHIFT,
}
```

**Comment by Kethku** [comment] 2021-06-09 19:24
Well that's somewhat concerning :l I wonder if this will have to wait for the upstream keyboard PRs...

Looks like there is an issue that captures this: https://github.com/rust-windowing/winit/issues/812

I wonder if the short term fix is to use scancodes which do seem to be present. We could modify the keyboard mappings to use them rather than the virtual keycodes

**Comment by last-partizan** [comment] 2021-06-13 07:16
I just switched to test opengl branch, and for me (using EN layout) it breaks some Shift combiantions as well.

None of the `Shift + number` works, except for `Shift + 2` -> `@`.

I'm using wayland by the way.

**Comment by Kethku** [comment] 2021-06-13 18:02
Ok after I merge opengl I'm gonna look into this. I'll probably have to swap to scan codes while we wait for upstream keyboard PRs to merge.

**Comment by Kethku** [comment] 2021-06-13 23:22
Actually I'm going to close this in favor of the existing keyboard issue. I'll mention in that thread that scancodes will probably be necessary in the short run.

**Closed by Kethku** 2021-06-13 23:22 UTC
Labels: Keyboard Input
