### ISSUE TITLE
Font weight possibly not standard

### ISSUE THREAD

**Issue by p00f** [Kethku/neovide#327] opened 2020-07-18 05:47 UTC
1) Fallback doesn't work
2) Italic works for some fonts but doesn't for others

3)

-  Fonts are bolder - see text in tilix vs neovide
-  Fonts ~~are wider~~ have more spacing - see tabline in tilix vs neovide

![Screenshot from 2020-07-18 11-13-27](https://user-images.githubusercontent.com/36493671/87845755-bcdfb700-c8e7-11ea-86a8-d2cae78f449b.png)

4) Letters are not in the same horizontal level - see tabline in the above screenshot, also `else` on line 20 (relativenumber 11+9), also the quotes in vim-startify

**Comment by PitcherTear22** [comment] 2020-07-18 06:00
OS - arch linux
Version - https://github.com/Kethku/neovide/actions/runs/160252742

**Comment by lonkaars** [comment] 2020-07-22 06:00
![image](https://user-images.githubusercontent.com/32883851/88139927-fe76a780-cbf0-11ea-86f8-ac63eb8c80ad.png)
JetBrainsMono NF
![image](https://user-images.githubusercontent.com/32883851/88139991-2960fb80-cbf1-11ea-9f9d-e55ff222baef.png)
FiraCode NF

I have the same issue but it only seems to happen when I use JetBrains Mono as my font. I'm also on Arch Linux

**Comment by PitcherTear22** [comment] 2020-07-22 14:45
Hmm that fixes the "not same horizontal level" problem, but the other problems are still there (using Roboto Mono)
![Screenshot from 2020-07-22 20-13-46](https://user-images.githubusercontent.com/36493671/88190601-17667380-cc58-11ea-80c9-f0da8784ce49.png)

**Comment by PitcherTear22** [comment] 2020-07-22 18:11
Changed "wider" to "more spaced" in the top comment

**Comment by lonkaars** [comment] 2020-07-23 11:43
Font kerning is something you might be able to change in your terminal emulator of choice. Regular fonts have embedded kerning information because the glyphs have different widths, but monospaced fonts don't have different widths. I use st as my terminal and don't notice any difference apart from the horizontal alignment issue

**Comment by PitcherTear22** [comment] 2020-07-23 12:30
Yeah but the problem is in neovide not terminal - gnome terminal, tilix and konsole all do it properly

**Comment by Kethku** [comment] 2020-07-27 17:38
This sounds like the font in question reports metrics differently than we expect. Let me go track down where that is computed

**Comment by Kethku** [comment] 2020-07-27 17:47
https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L312 this is where the system takes some text and turns it into a shaped text blob which we can actually render. I suppose its possible that your font does something weird requiring vertical kerning as well as horizontal. That would likely explain the vertical positioning issue.

Italic inline is probably just something that was never built yet. Its been a while since I touched that code, but it should be possible to include. A problem that may not be obvious is that we have load and cache the font associated with each type of font characteristic. So the code is somewhat sensitive and if done incorrectly, it can take up a bunch of ram, increase startup time, or both.

Lastly, the computed metrics are responsible for the font spacing https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L350. Basically we take a standard character string: https://github.com/Kethku/neovide/blob/master/src/renderer/caching_shaper.rs#L350 and compute the maximum width for that character. This is a good middle ground solution which handles most fonts I threw at it, but is likely to be slightly different than terminal renderer xyz. Maybe we could introduce a setting which allows you to tweek the spacing? What do you think?

Unfortunately this project has slowed due to *insert global catastrophe here*. I'm still invested in working on it, but it will take time, and we could always use contributors. I'm totally happy to help someone interested in digging in though! We have the gitter linked in the readme if you want to chat there.

**Comment by nganhkhoa** [comment] 2020-08-15 08:30
I don't know if I should add into the issue, or create a new one. Here's what I found about font fallback.

This `break` here

https://github.com/Kethku/neovide/blob/d406cf6c3154090cf3056b0d21fe850af2c49b88/src/renderer/caching_shaper.rs#L195-L202

stops the processing of font fallbacks. If loaded successfully with `guifont=Font\ 1, Font\ 2:h14`, `font_name` will iterate through the list of fonts. If it finds the first font, neovide does not load other fonts into cache.

I tried with my setup for Korean, Japanese, and Chinese as fallbacks to "FiraCode Nerd Font". After debugging through, I see this breaks and only "FiraCode Nerd Font" is loaded.

```vim
set guifont=FiraCode\ Nerd\ Font\ Mono,Gulim,Yu\ Mincho,NSimSun:h16
```

Here's what after:
![image](https://user-images.githubusercontent.com/29661303/90308650-5e6c1f80-df0b-11ea-92e8-bb19f36a9ec2.png)


Before removing the break:
![image](https://user-images.githubusercontent.com/29661303/90308656-70e65900-df0b-11ea-99ea-afffd0a85549.png)

P/S: The vim help on guifont and many tutorials online specified `guifont=Font_1` to be the same as `guifont=Font\ 1`, which is not true in Neovide case. Neovide uses [font_kit](https://docs.rs/font-kit/0.10.0/font_kit/source/trait.Source.html) and font_kit searches for fonts with space. So we might as well stated in our docs that only "Font\ 1" to be used.

P/S 2: I cannot use Microsoft IME with Neovide.

**Comment by p00f** [comment] 2020-08-23 20:31
^(pls decrease font weight/add an option. point no 3, subpoint 1)

**Comment by j4qfrost** [comment] 2020-08-23 21:27
@p00f aaa shoot I closed it prematurely.

**Comment by Kethku** [comment] 2020-08-28 03:56
@p00f I would love any assistance or investigation you might be able to contribute. https://github.com/Kethku/neovide/issues/327#issuecomment-664542895 gives a pretty comprehensive description of the moving parts.

The specifics of font weight are largely default from skia. That said, if there is a way to configure font weight in skia, adding settings for such a thing would be pretty easy.

**Comment by p00f** [comment] 2020-08-28 05:14
> Font weight possibly not standard, and vertical alignment is messed up with some fonts

Vertical alignment has been fixed ig

**Comment by p00f** [comment] 2020-08-28 05:23
> @p00f I would love any assistance or investigation you might be able to contribute. #327 (comment) gives a pretty comprehensive description of the moving parts.

oof i just asked them not to close the issue

**Comment by Kethku** [comment] 2020-08-28 06:49
Did not intend to close this. Its fine if you don't want to help or contribute, but it may be a bit before we get to font tweaking as there are other bugs and features to complete. Let me know if you do end up poking around

**Comment by p00f** [comment] 2020-08-28 07:58
I'll start contributing after exactly one month.

**Comment by Kethku** [comment] 2021-06-13 23:46
Closing in favor of https://github.com/Kethku/neovide/issues/589

**Closed by Kethku** 2021-06-13 23:46 UTC
Labels: Font Fallback, bug
