### ISSUE TITLE
Linux OpenGL: cursor position is off (and gets worse) with every new character

### ISSUE THREAD

**Issue by mikkovedru** [Kethku/neovide#692] opened 2021-05-27 20:46 UTC
The 3-point list of remaining OpenGL Linux issues mentioned in #655, says:
> The cursor is frequently **slightly** off from the grid. I believe this stems from the font hinting work
>(...)
>I think problem 1 can be ignored for merge.

Perhaps we have a different definition of "slight", but the current condition and the offset in my case are so big, that the software is unusable and is not in the can-be-released condition.

A couple of illustrations are in order. 

Here is the screenshot with insert mode in and me just typing all the keyboard characters one by one, without repeating.
![image](https://user-images.githubusercontent.com/2521942/119891563-cbecb800-bf41-11eb-8be8-ca130559ebb1.png)
The cursor should be shown immediately after `m`, but is way farther than that. Roughly speaking about 2 characters width away from where it should be.

Then I pressed Esc and see this:
![image](https://user-images.githubusercontent.com/2521942/119891963-3dc50180-bf42-11eb-949b-3ae1bde66d08.png)
As I said, no character is being repeated, so we actually see the same `m` letter being displayed twice, even with some extra-extra space in between them.

Then I go one position to the left.
![image](https://user-images.githubusercontent.com/2521942/119892193-8ed4f580-bf42-11eb-8a59-0a7d38bca867.png)
As you can see, it is totally unusable, especially with the normal text.

### First
While writing this bug report I also realized something, that is hopefully new information for you as well.

The cursor offset is not constant, but is being worsened by each newly typed character.

So when there are only a few characters, it is _somewhat_ fine.
![image](https://user-images.githubusercontent.com/2521942/119893278-d445f280-bf43-11eb-8da3-02484ab3fa7b.png)

But the longer the line becomes, the worse the situation and the offset gets:
![image](https://user-images.githubusercontent.com/2521942/119893348-ec1d7680-bf43-11eb-80fd-0b2bb00eab24.png)

![image](https://user-images.githubusercontent.com/2521942/119893382-f3dd1b00-bf43-11eb-99b0-c47f273f24d6.png)

![image](https://user-images.githubusercontent.com/2521942/119893411-fccdec80-bf43-11eb-9e28-37296e9d47fe.png)

![image](https://user-images.githubusercontent.com/2521942/119893438-07888180-bf44-11eb-8d69-e560e10ed925.png)

![image](https://user-images.githubusercontent.com/2521942/119893494-1c651500-bf44-11eb-9367-18026a2a0b07.png)

### Second
Now that I reported the issue and was previewing before submitting, I also noticed an interesting pattern in the screenshots I sent, that github has to show smaller due to excessive width. Do you notice anything interesting here?:
![image](https://user-images.githubusercontent.com/2521942/119893668-5209fe00-bf44-11eb-80da-1bb6013ed9b0.png)

The cursor offset is entirely dependent and proportional to the width of the line, no matter how big the line is. Which - now that I think of it - makes total sense.

## Technical background
- Linux Mint 20.1 Cinnamon (4.8.6), based on Ubuntu 20.04
- Kernel 5.8.0-53-generic
- GeForce GTX 650, Nvidia drivers 390
- X, OpenGL (I successfully converted the Vulkan version, but was not able to run it).
- I am using a [Finnish (Scandinavian) keyboard layout](http://kbdlayout.info/KBDFI/) with my own changes.

**Comment by Kethku** [comment] 2021-05-27 21:55
The cursor positioning being off that I encountered was on the vertical axis not horizontally. I have modified the pull request message with a 4th issue that captures what you're talking about and have made a short addendum to the description explaining how I think it should be fixed.

I appreciate the investigation! its helpful to understand what the problem is

**Comment by Kethku** [comment] 2021-06-13 22:53
This has been fixed. When you get a chance, @mikkovedru could you pull verify that it has been fixed? Its likely by the time you see this that I will have merged opengl into main, so I would test from there.

**Comment by Kethku** [comment] 2021-06-13 22:54
Closing for now, but reopen if I'm wrong :)

**Closed by Kethku** 2021-06-13 22:53 UTC
Labels: bug
