### ISSUE TITLE
Quit doesn't Quit

### ISSUE THREAD

**Issue by exoticus** [Kethku/neovide#226] opened 2020-03-31 23:15 UTC
Continuing on #221, I tried @j4qfrost 's temporary solution to put process::exit after ui loop breaks and it seems to have alleviated the crashing problem however, (`:q` | `:qa`) doesn't quit Neovide, instead the window freezes. the animation loop seems to stop but the window doesn't exit anyway.

Reproduction (on Mojave)
1. Open new Neovide in an empty buffer
2. `:q`

**Comment by j4qfrost** [comment] 2020-03-31 23:27
@Kethku Haha this is funny, I remember why I made the SDL window an option now when I was trying to embed neovide into my project. Being able to set window to None seems to fix this problem, since it explicitly drops the Window object. I'm learning to make my changes more granular to avoid forgetting.

**Comment by Kethku** [comment] 2020-03-31 23:30
I'm planning on reworking the quit logic to be more organized. At the moment its sorta spread around and adhock. Using process.exit to quit seems like not the best of options.

The hint that the Window object is a big source of the issue is a good one though that I will keep in mind.

**Comment by j4qfrost** [comment] 2020-03-31 23:34
As a cleaner way to handle this, we can implement the Drop trait for the WindowWrapper and change window to a ManuallyDrop object the same way the skulpin Renderer implements its drop method. Looking at my implementation using Option for the window is kind of an eyesore.

**Comment by exoticus** [comment] 2020-04-01 12:30
@j4qfrost i don't think the problem is caused by window object not being dropped though, The issue seems to be that Neovide doesn't handle `:q` so that neovim exits but Neovide doesn't know about it... debugging kinda confirms that because the sdl window quit event doesn't even hit when you quit vim with `:q`

**Comment by exoticus** [comment] 2020-04-01 12:35
@j4qfrost I don't think WindowWrapper not being dropped is the culprit here. After debugging it seems that Neovide doesn't handle quitting vim through the `:q` which causes neovim to quit while neovide still thinks it's there. 

I think this can be solved by handling quit event and notifying sdl about that so that Event::Quit gets called

**Comment by j4qfrost** [comment] 2020-04-01 21:47
https://github.com/j4qfrost/neovide/tree/embed

Dropping is definitely the issue. My embedded version doesn't have this issue. I don't want to merge it into the master branch, because I think there's a better way to implement this.

**Comment by exoticus** [comment] 2020-04-01 22:21
@j4qfrost did you try to debug it, because you can see that executing `:q` doesn't break the ui loop, so even though your embed trick seems to fix it i think the primary issue is what i am describing. I might be wrong though so pease try to debug it to see

**Comment by j4qfrost** [comment] 2020-04-01 22:48
I don't want to come off as harsh, but I really want this message to sink in.

What do you mean by "debug it"? What steps did you take? I've seen your issue happen with master. I did the exact things that you described in your original post with my embed branch, and the window closes as desired. If I can't recreate your issues the way that you do, then it's a lot harder to attempt to fix your problem. As far as debugging the problem from my side of things, I have spent a number of hours with this among other issues, and in that time I've learned a lot, which is enough to say with a fair amount of certainty that this is what is causing you to run into the ghost window. I take it that you haven't run my branch, but I'm not sure what more I can offer past, producing the desired behavior. The problem is that the window doesn't get destroyed explicitly once the program exits, and in my embed branch I've explicitly allowed for the window to be destroyed before process::exit is called.

**Comment by Kethku** [comment] 2020-04-01 22:52
@exoticus I'm invested in fixing your issue as well, and I think we aren't that far off. One thing that may not be obvious is that as far as I can tell, there isn't an exit event for the neovim process. That said I could very well be wrong. Do you have a link to the docs for an event that does what you are describing?

**Comment by Kethku** [comment] 2020-04-01 22:56
Further, this exact scenario has worked in the past. So I'm confident we can figure it out

**Comment by Kethku** [comment] 2020-04-01 23:01
To be more concrete, today the way we get notified if the neovim process has closed is by awaiting this promise: https://github.com/Kethku/neovide/blob/master/src/bridge/mod.rs#L109

Once that promise resolves, we can be sure that the neovim process has closed. Until recently we would then trigger an app closure by calling process.exit. This was recently changed to make the app more maintainable and modular to setting a variable instead.

This is a more principled approach but brought to the forefront the issue that @j4qfrost has been investigating which has to do with the window not getting dropped properly. In the meantime you may find success in using the released binaries to run, or building from an older commit such as this one: https://github.com/Kethku/neovide/commit/703b7bbe5bd25d6009c0162702b494405f45ed8c

**Comment by exoticus** [comment] 2020-04-02 12:20
@j4qfrost Few things to make clear here, First of all i am not complaining or asking for you to fix _my problem_, in the contrary i am trying my best to help with fixing it. So again if i came as needy or demanding, rest assured this wasn't my intention and i am sorry if you felt that way. It's just that i really like neovide and am trying to be helpful.

Second about the issue, Your branch shouldn't have that problem because you have this https://github.com/j4qfrost/neovide/blob/0bef531902b657c7d5061128ec230316ad056c0e/src/window.rs#L265 which handles if neovim bridge isn't working and sets the window to None which in turn breaks the loop.

Back to the master branch, and by _debugging it_ i mean attaching a debugger to the process and watch if the loop is broken after you type `:q`, which it doesn't. It keeps running even though neovim has quit, that's the reason the ghost window happens. It isn't because of the window itself being stuck and not dropped. So what you say here
>The problem is that the window doesn't get destroyed explicitly once the program exits, and in my embed branch I've explicitly allowed for the window to be destroyed before process::exit is called.


isn't quite accurate because the program doesn't even leave the loop and process::exit isn't even reached

**Comment by exoticus** [comment] 2020-04-02 12:24
> In the meantime you may find success in using the released binaries to run, or building from an older commit such as this one: 703b7bb

@Kethku i am not looking for something that works, i am trying to share my findings to help. I hope my message above helped clear the situation a little bit

**Comment by exoticus** [comment] 2020-04-02 13:03
@j4qfrost to further prove my point i have edited your `embed` branch and [removed](https://github.com/exoticus/neovide/commit/02f2f09aae7e0f04e75857cd8ba0df6fd632bc4e) all the Option stuff and didn't set window to None, and it `:q` still works because the loop still breaks just fine because of [this](https://github.com/exoticus/neovide/blob/02f2f09aae7e0f04e75857cd8ba0df6fd632bc4e/src/window.rs#L260)

**Comment by Kethku** [comment] 2020-04-03 22:59
Okeydokey. I believe this is fixed by #231 which got merged. Thanks so much for working together on this and getting a short term solution while keeping general organization in mind.

Something that may not be obvious @exoticus is that there has been an effort in the past couple weeks to refactor neovide so that it could be embedded in other projects. Calling process.exit is a brute force way of forcing the application to close which wouldn't work if neovide is embedded in another application. There is an effort under way to close by causing each thread to stop individually. This was in progress and as you found out had some other issues as well.

I do think its reasonable to have the process.exit call so that master is still in a workable state, but long term I don't think its the way we will be going since it causes embedding to fail.

Longer term I think this problem would be made simpler by extracting the running management to a centralized component, and standardizing the way that other components read or quit themselves. I have some ideas and a local branch which gets this started, so I'll make a PR for further discussion in the coming days

**Comment by Kethku** [comment] 2020-04-03 22:59
Closing for now as the root issue is complete. Thanks again for the discussion

**Closed by Kethku** 2020-04-03 22:59 UTC
Labels: bug
